name: farskapsportal-ui
ingresses:
  - https://farskapsportal.dev.nav.no
  - https://farskapsportal.ekstern.dev.nav.no
host:
  - dekoratoren.ekstern.dev.nav.no
application:
  - farskapsportal-api
env:
  ENV: dev
  DEKORATOREN_URL: https://dekoratoren.ekstern.dev.nav.no
  FARSKAPSPORTAL_API_URL: http://farskapsportal-api
  LOGINSERVICE_URL: https://loginservice.dev.nav.no/login
  ENONIC_BOKMAAL: https://www.dev.nav.no/erklaer-farskap
  ENONIC_NYNORSK: https://www.dev.nav.no/erklaer-farskap/nn
  ENONIC_ENGELSK: https://www.dev.nav.no/erklaer-farskap/en
