name: farskapsportal-ui
ingresses:
  - https://farskapsportal.dev.nav.no
host:
  - dekoratoren.dev.nav.no
  - farskapsportal-api.dev.nav.no
env:
  NODE_ENV: production
  DEKORATOREN_URL: https://dekoratoren.dev.nav.no
  FARSKAPSPORTAL_API_AUDIENCE: dev-gcp:farskapsportal:farskapsportal-api
  FARSKAPSPORTAL_API_URL: https://farskapsportal-api.dev.nav.no
  FRONTENDLOGGER_BASE_URL: https://www-q0.nav.no/frontendlogger
