name: farskapsportal-ui
ingresses:
  - https://farskapsportal.ekstern.dev.nav.no
host:
  - dekoratoren.ekstern.dev.nav.no
application:
  - farskapsportal-api
env:
  ENV: dev
  DEKORATOREN_URL: https://dekoratoren.ekstern.dev.nav.no
  FARSKAPSPORTAL_API_URL: http://farskapsportal-api
  LOGINSERVICE_URL: https://loginservice.ekstern.dev.nav.no/login
