apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: {{ name }}
  namespace: farskapsportal
  labels:
    team: farskapsportal
spec:
  image: {{ image }}
  port: 8080
  replicas:
    min: 2
    max: 2
    cpuThresholdPercentage: 50
  idporten:
    enabled: true
    sidecar:
      enabled: true
      autoLogin: true
  tokenx:
    enabled: true
  liveness:
    path: /internal/isAlive
    initialDelay: 10
  readiness:
    path: /internal/isReady
    initialDelay: 10
  ingresses:
  {{#each ingresses as |url|}}
    - {{url}}
  {{/each}}
  env:
  {{#each env}}
    - name: {{@key}}
      value: "{{this}}"
  {{/each}}
    - name: APP_VERSION
      value: {{ image }}
  envFrom:
    - secret: farskapsportal-ui-maintenance-key
  accessPolicy:
    outbound:
      rules:
      {{#each application}}
        - application: "{{this}}"
      {{/each}}
      external:
      {{#each host}}
        - host: "{{this}}"
      {{/each}}
