name: farskapsportal-ui
ingresses:
  - https://farskapsportal.nav.no
host:
  - www.nav.no
  - farskapsportal-api.nav.no
env:
  DEKORATOREN_URL: https://www.nav.no/dekoratoren
  FARSKAPSPORTAL_API_URL: https://farskapsportal-api.nav.no
  FRONTENDLOGGER_BASE_URL: https://www.nav.no/frontendlogger
  LOGINSERVICE_URL: https://loginservice.nav.no/login
