name: farskapsportal-ui
ingresses:
  - https://farskapsportal.nav.no
  - https://farskapsportal.intern.nav.no
host:
  - nav.no
  - farskapsportal-api.nav.no
application:
  - farskapsportal-api
env:
  ENV: prod
  DEKORATOREN_URL: https://www.nav.no/dekoratoren
  FARSKAPSPORTAL_API_URL: http://farskapsportal-api.farskapsportal.svc.cluster.local
  FARSKAPSPORTAL_API_AUDIENCE: prod-gcp:farskapsportal:farskapsportal-api
  ENONIC_BOKMAAL: https://www.nav.no/erklaer-farskap
  ENONIC_NYNORSK: https://www.nav.no/erklaer-farskap/nn
  ENONIC_ENGELSK: https://www.nav.no/erklaer-farskap/en
