/* eslint-disable */
export default {
    'page.title': 'Elektronisk farskapserklæring',
    'frontpage.1.title': 'Hva innebærer det å erklære farskap?',
    'frontpage.1.desc': 'Hvis far og mor er gift, blir far automatisk registrert som far til barnet. Hvis far og mor ikke er gift må farskapet erklæres, helst innen barnets fødsel. Å erklære farskap gir far både rettigheter og plikter til barnet, som for eksempel:',
    'frontpage.1.li.1': 'Arverett',
    'frontpage.1.li.2': 'Foreldreansvar',
    'frontpage.1.li.3': 'Samværsrett',
    'frontpage.1.li.4': 'Barnebidrag',
    'frontpage.1.link': 'Les mer om loven på <a>https://www.regjeringen.no/bld/farskap</a>',
    'frontpage.2.title': 'Hva må til for å kunne erklære farskap elektronisk?',
    'frontpage.2.desc': 'For å erklære farskap elektronisk må disse vilkårene være oppfylt:',
    'frontpage.2.li.1': 'Både far og mor er folkeregistrert i Norge.',
    'frontpage.2.li.2': 'Dere venter barn sammen (er i svangerskapsuke 17 eller senere) eller har allerede fått barn der farskapet ikke er blitt erklært.',
    'frontpage.2.li.3': 'Mor og far er over 18 år.',
    'frontpage.2.li.4': 'Mor og far er enige om farskapet.',
    'frontpage.3.title': 'Hvordan erklæres farskapet elektronisk?',
    'frontpage.3.ol.1': 'Mor starter med å bekrefte farskapet:',
    'frontpage.3.ol.1.li.1': 'Hun oppgir termindato dersom barnet ikke er født. Hvis barnet er født ser hun barnet/barnas som ikke har farskap registrert.',
    'frontpage.3.ol.1.li.2': 'Hun oppgir fars navn og fødselsnummer (11 siffer).',
    'frontpage.3.ol.1.li.3': 'Mor bekrefter at oppgitt person er far til barnet/barna.',
    'frontpage.3.ol.2': 'Far bekrefter farskapserklæring på dittnav:',
    'frontpage.3.ol.2.li.1': 'Far logger inn og kontrollerer opplysningene.',
    'frontpage.3.ol.2.li.2': 'Far signerer farskapserklæringen.',
    'frontpage.login': 'Logg inn til elektronisk erklæring av farskap',
    'frontpage.inperson.title': 'Erklære farskapet gjennom oppmøte',
    'frontpage.inperson.desc': 'Hvis dere ikke oppfyller kravene til å erklære farskapet elektronisk må dere erklære farskapet ved å møte opp.',
    'frontpage.inperson.link': 'Finn ut hvordan',
}
