/* eslint-disable */
export default {
    'two': 'two',
    'three': 'three',
    'hour': 'hour',
    'hours': 'hours',
    'foedselsnummer': 'National identity number',
    'termindato': 'Estimated date of delivery',
    'navn': 'Name',
    'mor': 'Mother',
    'far': 'Father',
    'farskapserklaering': 'Declaration of paternity',

    'api.error': 'Whoops, something went wrong!',

    'form.feiloppsummering': 'To proceed, you must correct the following',
    'form.date.placeholder': 'dd.mm.yyyy',

    'error.taKontakt': 'Feel free to contact us at nav.no/contact or phone +47 55 55 33 33 for information on how to proceed to establish paternity',

    'withUserInfoError.banner.title': 'Whoops, ',
    'withUserInfoError.banner.text': 'something went wrong',
    'withUserInfoError.title': 'An error occurred while retrieving user information',
    'withUserInfoError.text': 'Please try again later',

    'breadcrumbs.forside': 'Declaration of paternity',
    'breadcrumbs.oversikt': 'Your declarations of paternity',
    'breadcrumbs.skjema': 'Declaration of paternity',
    'breadcrumbs.kvittering': 'Confirmation', // TODO receipt??
    'breadcrumbs.signer': 'Sign declaration of paternity',
    'breadcrumbs.avbrutt': 'Signing canceled', // TODO ok translation?

    'header.forside': 'Declaration of paternity',
    'header.oversikt': 'Your declarations of paternity',
    'header.skjema': 'Declaration of paternity',
    'header.kvittering': 'Confirmation', // TODO receipt??
    'header.signer': 'Sign declaration of paternity',
    'header.avbrutt': 'Signing was canceled', // TODO ok translation?

    'farskapserklaering.aboutChildren': 'Applies to children',
    'farskapserklaering.expectingChildren': 'Expecting a child',
    'farskapserklaering.bornChildren': 'Child(ren) born',
    'farskapserklaering.parents': 'Parents',
    'farskapserklaering.borSammen': 'Live together',
    'farskapserklaering.borSammen.yes': 'Yes',
    'farskapserklaering.borSammen.no': 'No',

    'forside.title': 'What does it mean to declare paternity',

    'forside.naarErklaeres.title': 'When does paternity have to be declared',
    'forside.naarErklaeres.content.1': 'Paternity does not follow directly from the law when the child\'s parents are not married to each other.',
    'forside.naarErklaeres.content.2': 'The normal procedure in such cases is that paternity is established by the mother of the child naming the father, and that he declares paternity. Paternity can be digitally declared by both parents electronically identifying themselves in a secure manner and signing a digital declaration',

    'forside.rettigheter.title': 'Rights and obligations',
    'forside.rettigheter.content': 'Declaring paternity of a child grants the father both rights and obligations towards the child, such as',
    'forside.rettigheter.arv.title': 'Inheritance',
    'forside.rettigheter.arv.content': 'Once paternity is validly established, the child has inheritance rights from the father',
    'forside.rettigheter.foreldreansvar.title': 'Parental responsibility',
    'forside.rettigheter.foreldreansvar.content.1': 'Parental responsibility is the right and duty of parents to take decisions for the child in personal matters. Parents shall exercise parental responsibility based on the child\'s needs and interests. The person or those who have parental responsibility are also the child\'s guardian',
    'forside.rettigheter.foreldreansvar.content.2': 'The mother and father have joint parental responsibility for children born after 1 January 2020. This applies to children who have married parents, children who have cohabiting parents and children whose parents do not live together.',
    'forside.rettigheter.foreldreansvar.content.3': 'If the mother wishes to have sole parental responsibility, she must notify the National Population Register within one year from the date on which the paternity has been established. If the father does not wish to have parental responsibility, he must notify the National Population Register within one year from the date on which the paternity has been established. If the mother has reported that she desires sole parental responsibility and the father desires parental responsibility or joint parental responsibility, he must take the matter to court himself.',
    'forside.rettigheter.barnebidrag.title': 'Child maintenance',
    'forside.rettigheter.barnebidrag.content': 'Both parents have a duty to provide for their child according to ability. When the parents do not live together, the person who does not live permanently with the child must pay child maintenance. The parents can enter into an agreement on the amount of the child maintenance. If the parents do not agree, each may demand that NAV determine the amount of the child maintenance. If the parents do not live together when the child is born, and they have not made an agreement concerning the support, NAV shall take the initiative to determine the support for the child.',
    'forside.rettigheter.samvaer.title': 'Access',
    'forside.rettigheter.samvaer.content.1': 'The child has a right of access to both parents even if they live apart. The parents have mutual responsibility for ensuring that the right of access is fulfilled.',
    'forside.rettigheter.samvaer.content.2': 'An agreement on parental responsibility, access or where the child will live permanently can be amended by a new agreement between the parents. If the parents do not agree, they can bring the case to court.',
    'forside.rettigheter.navn.title': 'Name',
    'forside.rettigheter.navn.content': 'Parents with parental responsibility can choose the name of the child. They must send notification of the name to <a>the National Population Register</a> (Norwegian Tax Administration). If the parents do not submit a last name within 6 months, the child will receive the mother\'s last name.',
    'forside.rettigheter.navn.link': 'https://www.skatteetaten.no/skjema/navnevalg/', // TODO /en
    'forside.rettigheter.linkLabel': '<a>Read more about the law on paternity</a>',
    'forside.rettigheter.link': 'https://lovdata.no/dokument/NL/lov/1981-04-08-7', // TODO /en

    'forside.hvem.title': 'Who can declare?',
    'forside.hvem.content.1': 'Both parents must have a Norwegian birth and personal identification number',
    'forside.hvem.content.2': 'Both parents must be over 18 years of age',

    'forside.naar.title': 'When can paternity be declared digitally',
    'forside.naar.content.1': 'Paternity can be declared digitally both before and after the child\'s birth',
    'forside.naar.content.2': 'Farskap kan tidligst erklæres når moren er i 22. svangerskapsuke', // TODO missing

    'forside.hvordan.title': 'How is paternity electronically declared?',
    'forside.hvordan.foer.title': 'Before birth',
    'forside.hvordan.foer.step.1': 'The mother lists the father',
    'forside.hvordan.foer.step.1.content.1': 'The mother logs into the paternity declaration solution',
    'forside.hvordan.foer.step.1.content.2': 'The mother enters her due date',
    'forside.hvordan.foer.step.1.content.4': 'The mother confirms that the person listed is the father of the child',
    'forside.hvordan.foer.step.2': 'The father declares paternity',
    'forside.hvordan.foer.step.2.content.1': 'The father receives notice from the mother or NAV with a link to the solution',
    'forside.hvordan.foer.step.2.content.2': 'The father logs in and checks the information',
    'forside.hvordan.foer.step.2.content.3': 'The father confirms he is aware of the legal implications of declaring paternity',
    'forside.hvordan.foer.step.2.content.4': 'The father signs the declaration',
    'forside.hvordan.foer.step.3': 'The declaration is sent to the National Population Register for registration and filing.',
    'forside.hvordan.etter.title': 'After the birth',
    'forside.hvordan.etter.step.1': 'The mother lists the father',
    'forside.hvordan.etter.step.1.content.1': 'The mother logs into the paternity declaration solution',
    'forside.hvordan.etter.step.1.content.2': 'The mother chooses the child whose father she wishes to list',
    'forside.hvordan.etter.step.1.content.3': 'The mother lists the father\'s name and national identity number (11 digits)',
    'forside.hvordan.etter.step.1.content.4': 'The mother confirms the person listed is child\'s father',
    'forside.hvordan.etter.step.2': 'The father declares paternity',
    'forside.hvordan.etter.step.2.content.1': 'The father receives notice from the mother or NAV with a link to the solution',
    'forside.hvordan.etter.step.2.content.2': 'The father logs in and checks the information',
    'forside.hvordan.etter.step.2.content.3': 'The father confirms he is aware of the legal implications of declaring paternity',
    'forside.hvordan.etter.step.2.content.4': 'The father signs the declaration',
    'forside.hvordan.etter.step.3': 'The declaration is sent to the National Population Register for registration and filing',

    'forside.alleredeRegistrert.title': 'Are you wondering if the paternity has already been registered?',
    'forside.alleredeRegistrert.content': 'If you have already had the child and both you and the father of the child have already signed the paternity, please contact the Norwegian Tax Administration (National Population Register)',
    'forside.alleredeRegistrert.link': 'https://www.skatteetaten.no/en/person/national-registry/birth-and-name-selection/paternity-and-parental-responsibility/',

    'forside.loginButton': 'Fill out paternity declaration',

    'notPermitted.forelderHarVerge': 'You are registered with a guardian in the National Population Register and can therefore not use the solution.', // TODO
    'notPermitted.ikkeMyndig': 'In order to declare paternity electronically, both parents must be over the age of 18.',
    'notPermitted.medmorEllerUkjent': 'The co-mother or person with an unknown role cannot use the solution', // TODO: endre tekst
    'notPermitted.morIkkeNorskBostedsadresse': 'In order to declare paternity electronically, you must be registered with a Norwegian residential address in the National Register.', // TODO
    'notPermitted.morSivilstandGift.1': 'You are married and your spouse is automatically registered as the father of the child you give birth to. If a man other than your spouse is the child\'s father, the paternity can be changed. This cannot be done electronically.',
    'notPermitted.morSivilstandGift.2': 'You can find more information about changing paternity <a>here</a>. You are also welcome to contact us at nav.no/contact or phone +47 55 55 33 33',
    'notPermitted.morSivilstandGift.link': 'https://www.nav.no/no/person/familie/farskap-og-morskap', // TODO /en
    'notPermitted.morSivilstandPartner.1': 'You are a married/registered partner and you and your spouse/partner must submit an application to the Norwegian Tax Administration in order to have the co-maternity registered.',
    'notPermitted.morSivilstandPartner.2': 'You can find information and the application form <a>here</a>',
    'notPermitted.morSivilstandPartner.link': 'https://www.skatteetaten.no/person/folkeregister/fodsel-og-navnevalg/soknad-om-medmorskap/', // TODO /en
    'notPermitted.morSivilstandUoppgitt': 'Your marital status is unspecified and you cannot create a declaration of paternity', // TODO: endre tekst

    'oversikt.infoPanel.greeting': 'Hi, {fornavn}',

    'oversikt.infoPanel.common.forBarn.termindato': 'expected to be born {termindato}',
    'oversikt.infoPanel.common.forBarn.foedselsnummer': 'with national identity number {fnr}',

    'oversikt.infoPanel.mor.utenBarn.1': 'If you\'re at least 22 weeks pregnant, you can enter the due date and provide information about the child\'s father so he can declare paternity electronically.',
    'oversikt.infoPanel.mor.utenBarn.2': 'You must have the full name and national identity number of the man you list as the father of the child.',
    'oversikt.infoPanel.mor.medBarn.1.single': 'We have received information about the child you have just given birth to:',
    'oversikt.infoPanel.mor.medBarn.1.multiple': 'We have received information about your recently born children:',
    'oversikt.infoPanel.mor.medBarn.2': 'According to our information, paternity has not been established for the above children. If you provide information about the father below, he can declare paternity electronically. Please note that you must have the full name and national identity number of the man you list as the father.',
    'oversikt.infoPanel.mor.ikkeSignert.1': 'You have started filling out a declaration for child',
    'oversikt.infoPanel.mor.ikkeSignert.2': 'If the information you have provided about the child\'s father is incorrect, or you are unsure who the child\'s father is, you can delete the declaration by contacting NAV at nav.no/contact or phone +47 55 55 33 33.',
    'oversikt.infoPanel.mor.farIkkeSignert.1': 'You have previously provided information about the father of the child',
    'oversikt.infoPanel.mor.farIkkeSignert.2': 'The father you have listed has not declared the paternity of the child. When he declares paternity, the declaration is sent to the Norwegian Tax Administration for registration. A copy of the declaration will also be sent to the address you have registered with NAV.',
    'oversikt.infoPanel.mor.farSignert.1': 'You have provided information about the father of the child who is',
    'oversikt.infoPanel.mor.farSignert.2': ', and stated that the father has declared paternity of the child.',
    'oversikt.infoPanel.mor.farSignert.3': 'The declaration has been submitted to the Norwegian Tax Administration for registration. A copy of the declaration has been sent to the e-mail address you have registered with NAV.',

    'oversikt.infoPanel.far.utenErklaering': 'No paternity declaration is waiting for your signature. In order for you to declare paternity electronically, the child\'s mother must first list you as the father of the child.',
    'oversikt.infoPanel.far.ikkeSignert': 'You are listed as the father of the child.', // TODO
    'oversikt.infoPanel.far.signert': 'You have declared paternity and the declaration has been submitted to the National Population Register for registration. A copy of the declaration has also been sent to the address you have registered with NAV.', // TODO

    'oversikt.ventendeErklaeringer.title': 'Overview',

    'oversikt.moreInfoPanels.erFarskapRegistrert.title': 'Are you unsure whether the paternity of the child has been registered?',
    'oversikt.moreInfoPanels.erFarskapRegistrert.content': 'If you have already given birth to a child and are wondering if the paternity has been registered, please contact the Norwegian Tax Administration. You can find more information about registering paternity <a>here</a>. If you have previously declared paternity electronically, the declaration must have been sent to the e-mail address you have registered with NAV.',
    'oversikt.moreInfoPanels.erFarskapRegistrert.link': 'https://www.skatteetaten.no/en/person/national-registry/birth-and-name-selection/children-born-in-norway/',
    'oversikt.moreInfoPanels.hvemErFar.title': 'Are you unsure who the father of the child is?',
    'oversikt.moreInfoPanels.hvemErFar.content': 'If you do not have a full name and national identity number or are unsure who the father of the child is, you cannot use the solution. If paternity is not established when the child is born, we will contact you to establish paternity. If you have any questions about the proceedings or otherwise, please contact us at nav.no/contact or phone +47 55 55 33 33.',
    'oversikt.moreInfoPanels.medmor.title': 'Would you like to list a co-mother?',
    'oversikt.moreInfoPanels.medmor.content.1': 'A co-mother is a woman who has been granted legal status as a parent of the biological child of her female spouse or cohabitant. If you are cohabiting with a woman, you can apply for co-maternity if the child has been conceived by means of assisted fertilisation.',
    'oversikt.moreInfoPanels.medmor.content.2': 'You can find information and the application form <a>here</a>',
    'oversikt.moreInfoPanels.medmor.content.link': 'https://www.skatteetaten.no/en/person/national-registry/birth-and-name-selection/application-for-joint-maternity/',
    'oversikt.moreInfoPanels.hvaSkjerNaa.title': 'What happens now?',
    'oversikt.moreInfoPanels.hvaSkjerNaa.content': 'The Norwegian Tax Administration is responsible for registering and filing paternity certificates in the National Population Register. When you submit information about your child\'s name to them, you will receive confirmation of the registration of the child\'s national identity number and name. You will receive the confirmation in your Altinn inbox. You can find more information about registering paternity and choice of name <a>here</a>.',
    'oversikt.moreInfoPanels.hvaSkjerNaa.link': 'https://www.skatteetaten.no/en/person/national-registry/birth-and-name-selection/children-born-in-norway/',
    'oversikt.moreInfoPanels.farErklaererIkke.title': 'What happens if the father you have listed does not declare paternity?',
    'oversikt.moreInfoPanels.farErklaererIkke.content': 'If the father you have listed does not declare paternity, NAV is responsible for establishing it. It may then be relevant to call in the parties and confirm paternity by means of DNA analysis. For further information, please contact us at nav.no/contact or phone +47 55 55 33 33.',
    'oversikt.moreInfoPanels.erklaereUtenMor.title': 'Do you want to declare paternity of a child without the child\'s mother listing you as the father of the child?',
    'oversikt.moreInfoPanels.erklaereUtenMor.content.1': 'If you want to declare paternity of a child and you have not been listed as the father, you can come in person to one of these places:',
    'oversikt.moreInfoPanels.erklaereUtenMor.content.li.1': 'Doctor/midwife in connection with pregnancy check-up/childbirth',
    'oversikt.moreInfoPanels.erklaereUtenMor.content.li.2': 'Tax office',
    'oversikt.moreInfoPanels.erklaereUtenMor.content.li.3': 'NAV office',
    'oversikt.moreInfoPanels.erklaereUtenMor.content.li.4': 'Judge',
    'oversikt.moreInfoPanels.erklaereUtenMor.content.li.5': 'Norwegian diplomatic or consular official, if you are abroad',
    'oversikt.moreInfoPanels.erklaereUtenMor.content.2': 'Remember to bring your ID.',
    'oversikt.moreInfoPanels.erklaereUtenMor.content.3': 'For more information, see <a>paternity and parenthood</a>, contact us at nav.no/contact or phone +47 55 55 33 33. If the child is born abroad, please note that the mother must have listed you as the father of the child before you can declare paternity.',
    'oversikt.moreInfoPanels.erklaereUtenMor.content.3.link': '', // TODO
    'oversikt.moreInfoPanels.alleredeErklaert.title': 'Have you already declared paternity and wonder what happens next?',
    'oversikt.moreInfoPanels.alleredeErklaert.content.1': 'The Norwegian Tax Administration is responsible for registering and filing paternity certificates in the National Population Register. When you submit information about your child\'s name to them, you will receive confirmation of the registration of the child\'s national identity number and name. You will receive the confirmation in your Altinn inbox',
    'oversikt.moreInfoPanels.alleredeErklaert.content.2': ' You can find more information about registering paternity and choice of name <a>here</a>',
    'oversikt.moreInfoPanels.alleredeErklaert.link': 'https://www.skatteetaten.no/en/person/national-registry/birth-and-name-selection/children-born-in-norway/',
    'oversikt.moreInfoPanels.erJegFar.title': 'What do I do if I\'m unsure whether I\'m the father of the child?',
    'oversikt.moreInfoPanels.erJegFar.content': 'If you declare paternity of the child, you cannot withdraw the declaration at a later time. If you are unsure whether you are the child\'s father, you should therefore not sign the declaration. NAV will then take responsibility for ensuring that the paternity is established. In this case, you may be summoned and requested to provide samples for DNA analysis. For further information, please contact us at nav.no/contact or phone +47 55 55 33 33.',

    'oversikt.barn.link.title': 'Create paternity declaration for children',
    'oversikt.barn.link.status': 'This child does not have a registered father in the National Population Register',

    'oversikt.erklaeringer.link.forelder.mor': 'from ',
    'oversikt.erklaeringer.link.forelder.far': 'with ', // TODO ??
    'oversikt.erklaeringer.link.status.signering-bruker': 'Waiting for your signature',
    'oversikt.erklaeringer.link.status.signering-motpart': 'Waiting for your opposite party’s signature',
    'oversikt.erklaeringer.link.status.registrering': 'Signed and sent to the National Population Register',
    'oversikt.goToSkjemaButton': 'Create paternity declaration',

    'skjema.next': 'Next',
    'skjema.cancel': 'Cancel',
    'skjema.edit': 'Change',
    'skjema.submit': 'Sign declaration of paternity',

    'skjema.borSammen.description.intro': 'Parents who do not live with the child are obliged to pay child maintenance.',
    'skjema.borSammen.description.content': 'When the parents do not live together when the child is born and have also not entered into an agreement on child maintenance, NAV will open a maintenance case and determine support on its own initiative. If you enter into an agreement and send information about this to us, we will not open a maintenance case. ',
    'skjema.borSammen.label.yes': 'Yes',
    'skjema.borSammen.label.no': 'No',
    'skjema.borSammen.validation.required': 'The information is required',

    'skjema.confirm.validation.required': 'You must confirm before the application can be submitted.',

    'skjema.mor.barn.title': 'Applies to children',
    'skjema.mor.barn.description': 'Enter the estimated date of delivery as calculated in the ultrasound examination. If you have a date for a planned caesarean, enter this date as the estimated date of delivery. You must be at least 22 weeks pregnant to create a declaration.',
    'skjema.mor.barn.termindato.validation.required': 'Estimated date of delivery is required',
    'skjema.mor.barn.termindato.validation.pattern': 'Invalid date',
    'skjema.mor.barn.termindato.validation.minDate': 'Cannot be more than three weeks back in time',
    'skjema.mor.barn.termindato.validation.maxDate': 'The date is more than 40 weeks ahead in time. Wait until week 22 of pregnancy to confirm the father of the child.',
    'skjema.mor.barn.termindato.validation.beforeWeek22': 'You are in week {weekNr} of the pregnancy. Wait until week 22 to confirm the father of the child.',
    'skjema.mor.far.title': 'The father of the child',
    'skjema.mor.far.navn.label': 'Name',
    'skjema.mor.far.navn.description.1': 'Enter your full name as stated in the National Population Register',
    'skjema.mor.far.navn.description.2': 'Enter the name as follows: first name middle name last name.',
    'skjema.mor.far.navn.validation.required': 'The name of the father is required',
    'skjema.mor.far.foedselsnummer.label': 'National identity number',
    'skjema.mor.far.foedselsnummer.validation.required': 'The national identity number of the father is required',
    'skjema.mor.far.foedselsnummer.validation.fnr': 'Invalid national identity number',
    'skjema.mor.far.validation.feilRolleFar.1': 'Co-maternity cannot be declared electronically. If you are cohabiting with a woman, you can apply to the Norwegian Tax Administration about co-maternity if the child has been conceived by means of assisted fertilisation.',
    'skjema.mor.far.validation.feilRolleFar.2': 'You can find information and the application form <a>here</a>',
    'skjema.mor.far.validation.feilRolleFar.link': 'https://www.skatteetaten.no/en/person/national-registry/birth-and-name-selection/application-for-joint-maternity/',
    'skjema.mor.far.validation.forskjelligeFedre': 'You can\'t create paternity declarations with different fathers for the same cohort of newborns', // TODO: skal denne kunne oppstå? Kanskje ikke tillate mor å taste inn annen far?
    'skjema.mor.far.validation.pdlPersonIkkeFunnet': 'The national identity number you have provided is not found in the National Population Register.',
    'skjema.mor.far.validation.defaultUgyldigFarMessage': 'The listed father cannot declare paternity digitally. For further information, please contact NAV at nav.no/contact or phone +47 55 55 33 33.',
    'skjema.mor.far.validation.maksAntallForsoek.1': 'You have entered the wrong national identity number/name of the listed father three times and have now been blocked from the solution.',
    'skjema.mor.far.validation.maksAntallForsoek.2': 'You can try again in',
    'skjema.mor.far.validation.morOgFarSammePerson': 'You can not register yourself as the father.',
    'skjema.mor.far.validation.navnStemmerIkkeMedRegister.1': 'The name and/or national identity number of the father of the child is incorrect.',
    'skjema.mor.far.validation.navnStemmerIkkeMedRegister.2': 'Check that the name is spelled correctly and that the national identity number is correct.',
    'skjema.mor.far.validation.resterendeForsoek': 'You have entered the wrong national identity number/name of the listed father {incorrectAttempts} times. Please ask the child\'s father to check how his name is written in the National Population Register before trying again. If you make five incorrect entries you will be blocked from the solution.',
    'skjema.mor.far.validation.resterendeForsoek.final': 'You have entered the wrong national identity number/name of the listed father two times and have only one attempt left before you will be blocked from the solution.',
    'skjema.mor.borSammen.title': 'Do you live with the father of the child?',
    'skjema.mor.confirm.title': 'Confirm information about the father of the child',
    'skjema.mor.confirm.farCorrect.label': 'I approve that the information about the child\'s father is correct.',
    'skjema.mor.confirm.cannotWithdraw.label': 'I am aware that I cannot withdraw this confirmation later.',
    'skjema.confirm.signeringPostenInfo': 'You will be redirected to Posten\'s solution for signing',

    'skjema.far.borSammen.title': 'Do you live with the mother of the child?',
    'skjema.far.lesOpplysninger.title': 'Read information provided by the child\'s mother',
    'skjema.far.confirm.title': 'Sign declaration of paternity',
    'skjema.far.confirm.readAndUnderstood.label': 'I\'ve read and understood what the paternity declaration entails.',
    'skjema.far.confirm.cannotWithdraw.label': 'I am aware that this confirmation cannot be withdrawn at a later date.',

    'kvittering.intro.foedselsnummer': 'with national identity number',
    'kvittering.intro.termindato': 'expected date of birth',
    'kvittering.intro.downloadPdfNotSigned': 'You can download the paternity declaration as a pdf on this page after both parties have signed.',
    'kvittering.intro.downloadPdf': 'Download the signed paternity declaration as a pdf here: ',
    'kvittering.intro.pdfName': 'Farskapserklæring.pdf',
    'kvittering.intro.mor.1': 'We have received your information about the father',
    'kvittering.intro.mor.2': 'The declaration will be forwarded to him for approval and signing.',
    'kvittering.intro.mor.3': 'You cannot change the information you have provided.',
    'kvittering.intro.mor.4': 'You can find the declarations here: ',
    'kvittering.intro.mor.farSignert': 'The father declared paternity of the child(ren) on {date}',

    'kvittering.intro.far.1': 'You have signed a paternity declaration {date} for the child(ren)',
    'kvittering.intro.far.2': 'The declaration is final and can\'t be changed.',
    'kvittering.intro.far.3': 'You can find declarations here: ',
    'kvittering.morAlert.1': 'The declaration is not valid until the listed father has signed.',
    'kvittering.morAlert.2': 'He can log in already now to Your NAV (Ditt NAV) and sign the declaration. We will also send him a reminder by e-mail and/or sms.',
    'kvittering.prosessIndikator.step.1': 'The mother lists the father',
    'kvittering.prosessIndikator.step.2': 'The father declares paternity',
    'kvittering.prosessIndikator.step.3': 'The declaration is sent to the National Population Register for registration and filing',
    'kvittering.hvaSkjerVidere.title': 'What happens next?',
    'kvittering.hvaSkjerVidere.1': 'The Norwegian Tax Administration is responsible for registering and filing paternity declarations in the National Population Register. You will be sent the declaration once both of you have signed it. After you have chosen the name of the child, you will receive a confirmation of the registration of the child\'s national identity number and name. You will receive the confirmation in your Altinn inbox.',
    'kvittering.hvaSkjerVidere.2': 'More information can be found here:',
    'kvittering.hvaSkjerVidere.link': 'https://www.skatteetaten.no/en/person/national-registry/birth-and-name-selection/',
    'kvittering.hvaSkjerHvis.title': 'What happens if?',
    'kvittering.hvaSkjerHvis.farSignererIkke.title': 'The father you have listed does not sign the declaration',
    'kvittering.hvaSkjerHvis.farSignererIkke.termindato.text': 'If the father you have listed has not signed the declaration within one month of birth, we will contact you to establish the paternity. If the child\'s father forgets to sign the declaration, please remind him to do so.',
    'kvittering.hvaSkjerHvis.farSignererIkke.foedselsnummer.text': 'If the listed father does not sign the declaration within one month, you will be contacted by NAV to have the paternity established. If the father has forgotten to sign the declaration, please remind him to do so',
    'kvittering.hvaSkjerHvis.foedtIUtlandet.title': 'The child is born abroad',
    'kvittering.hvaSkjerHvis.foedtIUtlandet.text': 'The electronic declaration is not valid if the child is born abroad. If this happens, you must re-declare the paternity on paper.',
    'kvittering.hvaSkjerHvis.barnetDoer.title': 'The child dies',
    'kvittering.hvaSkjerHvis.barnetDoer.text': 'If the child dies before the pregnancy reaches full term, the paternity will in some cases nevertheless be registered. Please contact the Norwegian Tax Administration if you have any questions about this.',
    'kvittering.ytelserOgTjenester.title': 'Related benefits and services from NAV',
    'kvittering.ytelserOgTjenester.foreldrepengerSvangerskapspengerEngangsstoenad.title': 'Parental benefit, pregnancy benefit and lump-sum grant',
    'kvittering.ytelserOgTjenester.foreldrepengerSvangerskapspengerEngangsstoenad.text': 'You can find information about your rights and application form here:',
    'kvittering.ytelserOgTjenester.foreldrepengerSvangerskapspengerEngangsstoenad.link': 'https://familie.nav.no',
    'kvittering.ytelserOgTjenester.barnetrygd.title': 'Child benefit',
    'kvittering.ytelserOgTjenester.barnetrygd.text': 'As a general rule, you do not need to apply for child benefit. If the child is born in Norway, the mother of the child will automatically receive child benefit about 2 months after giving birth. You can find more information about the right to child benefit here:',
    'kvittering.ytelserOgTjenester.barnetrygd.link': 'https://www.nav.no/en/home/benefits-and-services/relatert-informasjon/child-benefit#chapter-1',
    'kvittering.ytelserOgTjenester.utvidetBarnetrygd.title': 'Extended child benefit',
    'kvittering.ytelserOgTjenester.utvidetBarnetrygd.text': 'If you are a single mother or father, you can apply for extended child benefit. You can find more information here:',
    'kvittering.ytelserOgTjenester.utvidetBarnetrygd.link': 'https://www.nav.no/en/home/benefits-and-services/relatert-informasjon/child-benefit#chapter-1',
    'kvittering.ytelserOgTjenester.barnebidrag.title': 'Child maintenance',
    'kvittering.ytelserOgTjenester.barnebidrag.text': 'If you do not live with the other parent, you may be entitled to child maintenance. You can find more information here:',
    'kvittering.ytelserOgTjenester.barnebidrag.link': 'https://www.nav.no/en/home/benefits-and-services/relatert-informasjon/child-benefit#chapter-1',
    'kvittering.ytelserOgTjenester.stoenadTilEnsligMorEllerFar.title': 'Benefit for single mother or father',
    'kvittering.ytelserOgTjenester.stoenadTilEnsligMorEllerFar.text': 'You may be entitled to various support schemes if you are a single parent. You can find more information here:',
    'kvittering.ytelserOgTjenester.stoenadTilEnsligMorEllerFar.link': 'https://www.nav.no/familie/alene-med-barn',

    'signer.alert.1': 'You have filled out information about the father and child, but have not signed the form. Check if the information is correct and sign the form.',
    'signer.alert.2': 'If you would like to delete or change the declaration, please contact NAV at nav.no/contact or phone +47 55 55 33 33.',
    'signer.submit': 'Sign',
    'signer.cancel': 'Cancel',

    'avbrutt.alert.mor': '', // TODO missing
    'avbrutt.alert.far': '', // TODO missing
};
