/* eslint-disable */
export default {
    'two': 'to',
    'three': 'tre',
    'hour': 'time',
    'hours': 'timer',
    'foedselsnummer': 'Fødselsnummer',
    'termindato': 'Termindato',
    'navn': 'Navn',
    'mor': 'Mor',
    'far': 'Far',
    'farskapserklaering': 'Farskapserklæring',

    'api.error': 'Oisann, noe gikk galt!',

    'form.feiloppsummering': 'For å gå videre må du rette opp følgende:',
    'form.date.placeholder': 'dd.mm.åååå',

    'error.taKontakt': 'Ta gjerne kontakt med oss på nav.no/kontakt eller telefon 55 55 33 33 for å få informasjon om hvordan du skal gå frem for å få fastsatt farskap.',

    'withUserInfoError.banner.title': 'Oops,',
    'withUserInfoError.banner.text': 'noe gikk galt.',
    'withUserInfoError.title': 'Det oppstod en feil ved henting av brukerinformasjon',
    'withUserInfoError.text': 'Vennligst prøv igjen senere.',

    'breadcrumbs.forside': 'Farskapserklæring',
    'breadcrumbs.oversikt': 'Dine farskapserklæringer',
    'breadcrumbs.skjema': 'Skjema: Farskapserklæring',
    'breadcrumbs.kvittering': 'Kvittering',
    'breadcrumbs.signer': 'Signer farskapserklæring',
    'breadcrumbs.avbrutt': 'Signering avbrutt',

    'header.forside': 'Farskapserklæring',
    'header.oversikt': 'Dine farskapserklæringer',
    'header.skjema': 'Skjema: Farskapserklæring',
    'header.kvittering': 'Bekreftelse på innsendt farskapserklæring',
    'header.signer': 'Signer farskapserklæring',
    'header.avbrutt': 'Signering er avbrutt',

    'farskapserklaering.aboutChildren': 'Gjelder barn',
    'farskapserklaering.expectingChildren': 'Venter barn',
    'farskapserklaering.bornChildren': 'Født(e) barn',
    'farskapserklaering.parents': 'Foreldre',
    'farskapserklaering.borSammen': 'Bor sammen',
    'farskapserklaering.borSammen.yes': 'Ja',
    'farskapserklaering.borSammen.no': 'Nei',

    'forside.title': 'Hva innebærer det å erklære farskap?',

    'forside.naarErklaeres.title': 'Når må farskapet erklæres?',
    'forside.naarErklaeres.content.1': 'Når barnets foreldre ikke er gift med hverandre, følger ikke farskapet direkte av loven.',
    'forside.naarErklaeres.content.2': 'Det vanlige i slike tilfeller er at farskap etableres ved at moren til barnet oppgir hvem som er faren, og at han erklærer farskapet. Farskap kan erklæres digitalt ved at begge foreldrene identifiserer seg elektronisk på en sikker måte og signerer en digital erklæring.',

    'forside.rettigheter.title': 'Rettigheter og plikter',
    'forside.rettigheter.content': 'Å erklære farskap for et barn gir faren både rettigheter og plikter overfor barnet, som for eksempel:',
    'forside.rettigheter.arv.title': 'Arv',
    'forside.rettigheter.arv.content': 'Når farskapet er gyldig fastsatt, har barnet arverett etter far.',
    'forside.rettigheter.foreldreansvar.title': 'Foreldreansvar',
    'forside.rettigheter.foreldreansvar.content.1': 'Foreldreansvar er den rett og plikt foreldre har til å bestemme over barnet i personlige forhold. Foreldre skal utøve foreldreansvaret ut fra barnets behov og interesser. Den eller de som har foreldreansvar, er også barnets verge.',
    'forside.rettigheter.foreldreansvar.content.2': 'For barn som blir født etter 1. januar 2020 får mor og far felles foreldreansvar. Dette gjelder barn som har gifte foreldre, barn som har samboende foreldre og barn som har foreldre som ikke bor sammen.',
    'forside.rettigheter.foreldreansvar.content.3': 'Dersom mor ønsker å ha foreldreansvaret alene må hun melde fra til Folkeregisteret om det innen ett år fra den dagen farskapet er fastsatt. Dersom far ikke ønsker å ha foreldreansvar må han melde fra til Folkeregisteret om det innen ett år fra den dagen farskapet er fastsatt. Dersom mor har meldt inn at hun ønsker foreldreansvaret alene og far ønsker foreldreansvaret eller delt foreldreansvar må han selv ta saken til domstolen.',
    'forside.rettigheter.barnebidrag.title': 'Barnebidrag',
    'forside.rettigheter.barnebidrag.content': 'Begge foreldrene har plikt til å sørge for underholdet av barnet sitt etter evne. Når foreldrene ikke bor sammen, må den som ikke bor fast sammen med barnet betale barnebidrag. Foreldrene kan inngå avtale om barnebidragets størrelse. Dersom foreldrene ikke blir enige, kan hver av dem kreve at NAV fastsetter størrelsen på barnebidraget. Dersom foreldrene ikke lever sammen når barnet blir født, og de ikke har gjort avtale om bidraget, skal NAV av eget tiltak fastsette bidrag til barnet.',
    'forside.rettigheter.samvaer.title': 'Samvær',
    'forside.rettigheter.samvaer.content.1': 'Barnet har rett til samvær med begge foreldrene selv om de lever hver for seg. Foreldrene har gjensidig ansvar for at samværsretten blir oppfylt.',
    'forside.rettigheter.samvaer.content.2': 'En avtale om foreldreansvar, samvær eller hvor barnet skal bo fast, kan endres ved ny avtale mellom foreldrene. Dersom foreldrene ikke blir enige, kan de bringe saken inn for retten.',
    'forside.rettigheter.navn.title': 'Navn',
    'forside.rettigheter.navn.content': 'Foreldre med foreldreansvar kan velge navn til barnet. De må sende melding om navnet til <a>Folkeregisteret</a> (Skatteetaten). Hvis foreldrene ikke gir melding om etternavn innen 6 måneder, får barnet morens etternavn.',
    'forside.rettigheter.navn.link': 'https://www.skatteetaten.no/skjema/navnevalg/',
    'forside.rettigheter.linkLabel': '<a>Les mer om loven om farskap</a>',
    'forside.rettigheter.link': 'https://lovdata.no/dokument/NL/lov/1981-04-08-7',

    'forside.hvem.title': 'Hvem kan erklære?',
    'forside.hvem.content.1': 'Begge foreldrene må ha norsk fødsels- og personnummer',
    'forside.hvem.content.2': 'Begge foreldrene må være over 18 år',

    'forside.naar.title': 'Når kan farskap erklæres digitalt?',
    'forside.naar.content.1': 'Farskap kan erklæres digitalt både før og etter barnets fødsel',
    'forside.naar.content.2': 'Farskap kan tidligst erklæres når moren er i 22. svangerskapsuke',

    'forside.hvordan.title': 'Hvordan erklære farskap elektronisk?',
    'forside.hvordan.foer.title': 'Før fødselen',
    'forside.hvordan.foer.step.1': 'Mor oppgir far:',
    'forside.hvordan.foer.step.1.content.1': 'Mor logger inn i løsningen for farskapserklæring',
    'forside.hvordan.foer.step.1.content.2': 'Mor oppgir termindatoen',
    'forside.hvordan.foer.step.1.content.3': 'Mor oppgir farens navn og fødselsnummer (11 siffer)',
    'forside.hvordan.foer.step.1.content.4': 'Mor bekrefter at personen som er oppgitt er faren til barnet',
    'forside.hvordan.foer.step.2': 'Far erklærer farskap:',
    'forside.hvordan.foer.step.2.content.1': 'Far får melding fra mor eller NAV med lenke til løsningen',
    'forside.hvordan.foer.step.2.content.2': 'Far logger inn og kontrollerer opplysningene',
    'forside.hvordan.foer.step.2.content.3': 'Far bekrefter at han er kjent med rettsvirkningene av å erklære farskap',
    'forside.hvordan.foer.step.2.content.4': 'Far signerer erklæringen',
    'forside.hvordan.foer.step.3': 'Erklæringen oversendes Folkeregisteret for registrering og arkivering.',
    'forside.hvordan.etter.title': 'Etter fødselen',
    'forside.hvordan.etter.step.1': 'Mor oppgir far',
    'forside.hvordan.etter.step.1.content.1': 'Mor logger inn i løsningen for farskapserklæring',
    'forside.hvordan.etter.step.1.content.2': 'Mor velger barn hun vil oppgi far til',
    'forside.hvordan.etter.step.1.content.3': 'Mor oppgir fars navn og fødselsnummer (11 siffer)',
    'forside.hvordan.etter.step.1.content.4': 'Mor bekrefter at oppgitt person er barnets far',
    'forside.hvordan.etter.step.2': 'Far erklærer farskap',
    'forside.hvordan.etter.step.2.content.1': 'Far får melding fra mor eller NAV med lenke til løsningen',
    'forside.hvordan.etter.step.2.content.2': 'Far logger inn og kontrollerer opplysningene',
    'forside.hvordan.etter.step.2.content.3': 'Far bekrefter at han er kjent med rettsvirkningene av å erklære farskap',
    'forside.hvordan.etter.step.2.content.4': 'Far signerer erklæringen',
    'forside.hvordan.etter.step.3': 'Erklæringen oversendes Folkeregisteret for registrering og arkivering',

    'forside.alleredeRegistrert.title': 'Lurer du på om farskapet allerede er registert?',
    'forside.alleredeRegistrert.content': 'Har du allerede fått barn og både du og faren til barnet allerede har signert farskapet, ber vi deg  å ta kontakt med ta kontakt med Skatteetaten (Folkeregisteret):      ',
    'forside.alleredeRegistrert.link': 'https://www.skatteetaten.no/person/folkeregister/fodsel-og-navnevalg/farskap/',

    'forside.loginButton': 'Fyll ut erklæring om farskap',

    'notPermitted.ikkeMyndig': 'For at farskap skal kunne erklæres elektronisk, må begge foreldrene være over 18 år.',
    'notPermitted.medmorEllerUkjent': 'Medmor eller person med ukjent rolle kan ikke benytte løsningen', // TODO: endre tekst
    'notPermitted.morSivilstandGift.1': 'Du er gift og ektefellen din blir automatisk registrert som faren til barn du føder. Hvis det er en annen mann enn ektefellen din som er barnets far, kan farskapet endres. Dette kan ikke gjøres elektronisk.',
    'notPermitted.morSivilstandGift.2': 'Du finner mer informasjon om endring av farskap <a>her</a>. Du er også velkommen til å kontakte oss på nav.no/kontakt eller telefon 55 55 33 33.',
    'notPermitted.morSivilstandGift.link': 'https://www.nav.no/no/person/familie/farskap-og-morskap',
    'notPermitted.morSivilstandPartner.1': 'Du er gift/registrert partner og du og ektefellen/partneren din må sende en søknad til Skatteetaten for å få medmorskap registret.',
    'notPermitted.morSivilstandPartner.2': 'Du finner informasjon og søknadsskjema <a>her</a>.',
    'notPermitted.morSivilstandPartner.link': 'https://www.skatteetaten.no/person/folkeregister/fodsel-og-navnevalg/soknad-om-medmorskap/',
    'notPermitted.morSivilstandUoppgitt': 'Du har uoppgitt sivilstand og kan ikke opprette farskapserklæring', // TODO: endre tekst

    'oversikt.infoPanel.greeting': 'Hei, {fornavn}',

    'oversikt.infoPanel.common.forBarn.termindato': 'forventet født {termindato}',
    'oversikt.infoPanel.common.forBarn.foedselsnummer': 'med fødselsnummer {fnr}',

    'oversikt.infoPanel.mor.utenBarn.1': 'Hvis du er minimum 22 uker på vei kan du oppgi termindatoen og gi opplysninger om barnets far slik at han kan erklære farskapet elektronisk.',
    'oversikt.infoPanel.mor.utenBarn.2': 'Du må ha fullt navn og fødselsnummer til mannen du oppgir som faren til barnet.',
    'oversikt.infoPanel.mor.medBarn.1.single': 'Vi har fått opplysninger om barnet du nettopp har født:',
    'oversikt.infoPanel.mor.medBarn.1.multiple': 'Vi har fått opplysninger om dine nylige fødte barn:',
    'oversikt.infoPanel.mor.medBarn.2': 'Ifølge våre opplysninger er farskapet ikke fastsatt for ovennevnte barn. Hvis du gir opplysninger om faren nedenfor, kan han erklære farskapet elektronisk. Husk at du må ha fullt navn og fødselsnummer til mannen du oppgir som far.',
    'oversikt.infoPanel.mor.ikkeSignert.1': 'Du har begynt på en erklæring for barn',
    'oversikt.infoPanel.mor.ikkeSignert.2': 'Hvis opplysningene du har gitt om faren til barnet ikke stemmer, eller du er usikker på hvem som er faren til barnet, kan du slette erklæringen ved å ta kontakt med NAV på nav.no/kontakt eller telefon 55 55 33 33.',
    'oversikt.infoPanel.mor.farIkkeSignert.1': 'Du har tidligere gitt opplysninger om far til barn',
    'oversikt.infoPanel.mor.farIkkeSignert.2': 'Faren du har oppgitt har ikke erklært farskapet til barnet. Når han erklærer farskapet, blir erklæringen oversendt til Skatteetaten for registrering. En kopi av erklæringen blir også sendt til adressen du har registret hos NAV.',
    'oversikt.infoPanel.mor.farSignert.1': 'Du har gitt opplysninger om faren til barnet som er',
    'oversikt.infoPanel.mor.farSignert.2': ', og oppgitt far har erklært farskap for barnet.',
    'oversikt.infoPanel.mor.farSignert.3': 'Erklæringen er oversendt til Skatteetaten for registrering. En kopi av erklæringen er sendt til e-postadressen du har registret hos NAV.',

    'oversikt.infoPanel.far.utenErklaering': 'Det er ingen farskapserklæring som venter på din signatur. For at du skal kunne erklære farskap elektronisk må moren til barnet først oppgi deg som faren til barnet.',
    'oversikt.infoPanel.far.ikkeSignert': 'Du er oppgitt som faren til barnet.', // TODO
    'oversikt.infoPanel.far.signert': 'Du har erklært farskap og erklæringen er oversendt til Folkeregisteret for registrering. En kopi av erklæringen er også sendt til adressen du har registret hos NAV.', // TODO

    'oversikt.ventendeErklaeringer.title': 'Oversikt',

    'oversikt.moreInfoPanels.erFarskapRegistrert.title': 'Er du usikker på om farskapet for barnet er registrert?',
    'oversikt.moreInfoPanels.erFarskapRegistrert.content': 'Hvis du allerede har født et barn og lurer på om farskapet er registrert ber vi deg ta kontakt med Skatteetaten. Du finner mer informasjon om registrering av farskap <a>her</a>. Hvis du tidligere har erklært farskap elektronisk skal erklæringen ha blitt sendt til e-postadressen du har registrert hos NAV.',
    'oversikt.moreInfoPanels.erFarskapRegistrert.link': 'https://www.skatteetaten.no/person/folkeregister/fodsel-og-navnevalg/barn-fodt-i-norge/',
    'oversikt.moreInfoPanels.hvemErFar.title': 'Er du usikker på hvem som er faren til barnet?',
    'oversikt.moreInfoPanels.hvemErFar.content': 'Hvis du ikke har fullt navn og fødselsnummer eller er usikker på hvem som er faren til barnet kan du ikke bruke løsningen. Hvis farskapet ikke er fastsatt når barnet blir født, vil vi kontakte deg for å få fastsatt farskapet. Hvis du lurer på saksgangen eller annet, kan du kontakte oss på nav.no/kontakt eller telefon 55 55 33 33.',
    'oversikt.moreInfoPanels.medmor.title': 'Ønsker du å oppgi medmor?',
    'oversikt.moreInfoPanels.medmor.content.1': 'En medmor er en kvinne som har fått juridisk foreldrestatus for det biologiske barnet til sin kvinnelige ektefelle eller samboer. Hvis du er samboer med en kvinne, kan dere søke om medmorskap hvis barnet har blitt til ved hjelp av assistert befruktning.',
    'oversikt.moreInfoPanels.medmor.content.2': 'Du finner informasjon og søknadsskjema <a>her</a>.',
    'oversikt.moreInfoPanels.medmor.content.link': 'https://www.skatteetaten.no/person/folkeregister/fodsel-og-navnevalg/soknad-om-medmorskap/',
    'oversikt.moreInfoPanels.hvaSkjerNaa.title': 'Hva skjer nå?',
    'oversikt.moreInfoPanels.hvaSkjerNaa.content': 'Det er Skatteetaten ved Folkeregisteret som er ansvarlig for å registrere og arkivere farskapserklæringer. Når dere melder inn opplysninger om barnets navn til dem vil du motta en bekreftelse på registrering av fødselsnummer og navn. Bekreftelsen mottar du i innboksen din i Altinn. Du finner mer informasjon om registrering av farskap og navnevalg <a>her</a>.',
    'oversikt.moreInfoPanels.hvaSkjerNaa.link': 'https://www.skatteetaten.no/person/folkeregister/fodsel-og-navnevalg/barn-fodt-i-norge/',
    'oversikt.moreInfoPanels.farErklaererIkke.title': 'Hva skjer hvis faren du har oppgitt ikke erklærer farskapet?',
    'oversikt.moreInfoPanels.farErklaererIkke.content': 'Hvis faren du har oppgitt ikke erklærer farskapet, har NAV ansvaret for å fastsette det. Det kan da være aktuelt å kalle inn partene og bekrefte farskapet ved bruk av DNA-analyse. For ytterligere informasjon kan du kontakte oss på nav.no/kontakt eller telefon 55 55 33 33.',
    'oversikt.moreInfoPanels.erklaereUtenMor.title': 'Vil du erklære farskap for et barn uten at barnets mor har oppgitt deg som faren til barnet?',
    'oversikt.moreInfoPanels.erklaereUtenMor.content.1': 'Hvis du ønsker å erklære farskap for et barn og du ikke er blitt oppgitt som far, kan du møte personlig på ett av disse stedene:',
    'oversikt.moreInfoPanels.erklaereUtenMor.content.li.1': 'Lege/jordmor i forbindelse med svangerskapskontroll/fødsel',
    'oversikt.moreInfoPanels.erklaereUtenMor.content.li.2': 'Skattekontor',
    'oversikt.moreInfoPanels.erklaereUtenMor.content.li.3': 'NAV-kontor',
    'oversikt.moreInfoPanels.erklaereUtenMor.content.li.4': 'Dommer',
    'oversikt.moreInfoPanels.erklaereUtenMor.content.li.5': 'Norsk diplomatisk eller konsulær tjenestemann, hvis du er i utlandet',
    'oversikt.moreInfoPanels.erklaereUtenMor.content.2': 'Husk å ta med legitimasjon.',
    'oversikt.moreInfoPanels.erklaereUtenMor.content.3': 'For mer informasjon se <a>farskap og foreldreskap</a>, kontakt oss på nav.no/kontakt eller telefon 55 55 33 33. Vi gjør oppmerksom på moren må ha oppgitt deg som faren til barnet før du kan erklære farskap hvis barnet er født i utlandet.',
    'oversikt.moreInfoPanels.erklaereUtenMor.content.3.link': 'https://www.nav.no/no/person/familie/farskap-og-morskap/farskap-og-foreldreansvar',
    'oversikt.moreInfoPanels.alleredeErklaert.title': 'Har du allerede erklært farskap og lurer på hva som skjer nå?',
    'oversikt.moreInfoPanels.alleredeErklaert.content.1': 'Det er Skatteetaten ved Folkeregisteret som er ansvarlig for å registrere og arkivere farskapserklæringer. Når dere melder inn opplysninger om barnets navn til dem vil du motta en bekreftelse på registrering av fødselsnummer og navn. Bekreftelsen mottar du i innboksen din i Altinn.',
    'oversikt.moreInfoPanels.alleredeErklaert.content.2': ' Du finner mer informasjon om registrering av farskap og navnevalg <a>her</a>.',
    'oversikt.moreInfoPanels.alleredeErklaert.link': 'https://www.skatteetaten.no/person/folkeregister/fodsel-og-navnevalg/barn-fodt-i-norge/',
    'oversikt.moreInfoPanels.erJegFar.title': 'Hva gjør jeg hvis jeg er usikker på om jeg er faren til barnet?',
    'oversikt.moreInfoPanels.erJegFar.content': 'Hvis du erklærer farskap for barnet kan du ikke senere trekke erklæringen tilbake. Hvis du er usikker på om du er barnets far bør du derfor ikke signere erklæringen. NAV vil da ta ansvar for at farskapet blir fastsatt. Du kan i så fall bli innkalt og bedt om å gi prøve til DNA-analyse. For ytterligere informasjon kan du kontakte oss på nav.no/kontakt eller telefon 55 55 33 33.',

    'oversikt.barn.link.title': 'Opprett farskapserklæring for barn',
    'oversikt.barn.link.status': 'Dette barnet har ikke en registrert far i Folkeregisteret',

    'oversikt.erklaeringer.link.forelder.mor': 'fra ',
    'oversikt.erklaeringer.link.forelder.far': 'med ',
    'oversikt.erklaeringer.link.status.signering-bruker': 'Venter på din signering',
    'oversikt.erklaeringer.link.status.signering-motpart': 'Venter på motparts signering',
    'oversikt.erklaeringer.link.status.registrering': 'Signert og sendt til Folkeregisteret',
    'oversikt.goToSkjemaButton': 'Opprett farskapserklæring',

    'skjema.next': 'Neste',
    'skjema.cancel': 'Avbryt',
    'skjema.edit': 'Endre',
    'skjema.submit': 'Signer farskapserklæring',

    'skjema.borSammen.description.intro': 'Foreldre som ikke bor sammen med barnet har plikt til å betale barnebidrag.',
    'skjema.borSammen.description.content': 'Når foreldrene ikke bor sammen når barnet blir født og heller ikke har inngått en avtale om barnebidrag, skal NAV ta opp bidragssak og fastsette bidrag på eget tiltak. Hvis dere inngår en avtale og sender informasjon om dette til oss, vil vi ikke ta opp bidragssak.',
    'skjema.borSammen.label.yes': 'Ja',
    'skjema.borSammen.label.no': 'Nei',
    'skjema.borSammen.validation.required': 'Opplysningen er påkrevd',

    'skjema.confirm.validation.required': 'Du må bekrefte før søknaden kan sendes inn.',

    'skjema.mor.barn.title': 'Gjelder barn',
    'skjema.mor.barn.description': 'Legg inn termindatoen slik den er beregnet i ultralydundersøkelsen. Hvis du har fått en dato for planlagt keisersnitt, legger du inn denne datoen som termindato. Du må være minst 22 uker på vei for å opprette en erklæring.',
    'skjema.mor.barn.termindato.validation.required': 'Termindato er påkrevd',
    'skjema.mor.barn.termindato.validation.pattern': 'Ugyldig dato',
    'skjema.mor.barn.termindato.validation.minDate': 'Kan ikke være mer enn tre uker tilbake i tid',
    'skjema.mor.barn.termindato.validation.maxDate': 'Datoen er mer enn 40 uker fram i tid. Vent til uke 22 av svangerskapet med å bekrefte faren til barnet.',
    'skjema.mor.barn.termindato.validation.beforeWeek22': 'Du er i uke {weekNr} i svangerskapet. Vent til uke 22 med å bekrefte faren til barnet.',
    'skjema.mor.far.title': 'Faren til barnet',
    'skjema.mor.far.navn.label': 'Navn',
    'skjema.mor.far.navn.description.1': 'Oppgi fullt navn slik det står i Folkeregisteret',
    'skjema.mor.far.navn.description.2': 'Skriv navnet slik: fornavn mellomnavn etternavn.',
    'skjema.mor.far.navn.validation.required': 'Navnet til faren er påkrevd',
    'skjema.mor.far.foedselsnummer.label': 'Fødselsnummer',
    'skjema.mor.far.foedselsnummer.validation.required': 'Fødselsnummeret til faren er påkrevd',
    'skjema.mor.far.foedselsnummer.validation.fnr': 'Ugyldig fødselsnummer',
    'skjema.mor.far.validation.feilRolleFar.1': 'Medmorskap kan ikke erklæres elektronisk. Hvis du er samboer med en kvinne, kan dere søke Skatteetaten om medmorskap hvis barnet har blitt til ved hjelp av assistert befruktning.',
    'skjema.mor.far.validation.feilRolleFar.2': 'Du finner informasjon og søknadsskjema <a>her</a>',
    'skjema.mor.far.validation.feilRolleFar.link': 'https://www.skatteetaten.no/person/folkeregister/fodsel-og-navnevalg/soknad-om-medmorskap/',
    'skjema.mor.far.validation.forskjelligeFedre': 'Du kan ikke opprette farskapserklæringer med forskjellige fedre for samme kull nyfødte', // TODO: skal denne kunne oppstå? Kanskje ikke tillate mor å taste inn annen far?
    'skjema.mor.far.validation.pdlPersonIkkeFunnet': 'Fødselsnummeret du har oppgitt finnes ikke i Folkeregisteret.',
    'skjema.mor.far.validation.defaultUgyldigFarMessage': 'Den oppgitte faren kan ikke erklære farskap digitalt. Ta kontakt med NAV på nav.no/kontakt eller telefon 55 55 33 33 for ytterligere informasjon.',
    'skjema.mor.far.validation.maksAntallForsoek.1': 'Du har tastet feil fødselsnummer/navn på oppgitt far fem ganger og har nå blitt blokkert fra løsningen.',
    'skjema.mor.far.validation.maksAntallForsoek.2': 'Du kan prøve på nytt igjen om {timerIgjenForNullstillingAvForsoek} {tidsEnhet}.',
    'skjema.mor.far.validation.navnStemmerIkkeMedRegister.1': 'Navnet og/eller fødselsnummeret til faren til barnet er feil.',
    'skjema.mor.far.validation.navnStemmerIkkeMedRegister.2': 'Sjekk at navnet er stavet riktig og at fødselsnummeret stemmer.',
    'skjema.mor.far.validation.resterendeForsoek': 'Du har tastet feil fødselsnummer/navn på oppgitt far {incorrectAttempts} ganger. Vennligst be faren til barnet om å sjekke hvordan navnet hans er skrevet i Folkeregisteret før du prøver på nytt. Hvis du taster feil fem ganger vil du bli blokkert fra løsningen.',
    'skjema.mor.far.validation.resterendeForsoek.final': 'Du har tastet feil fødselsnummer/navn på oppgitt far fire ganger og har bare ett forsøk igjen før du vil bli blokkert fra løsningen.',
    'skjema.mor.spraak.title': 'Språk for erklæringen',
    'skjema.mor.spraak.description': 'Erklæringen skal sendes til far for signering på det språket du velger i dette steget. Hvis far ikke forstår norsk eller erklæringen skal brukes i utlandet bør du velge å opprette erklæringen på engelsk. Far kan ikke selv endre på dette.',
    'skjema.mor.spraak.label.norwegian': 'Norsk',
    'skjema.mor.spraak.label.english': 'Engelsk (English)',
    'skjema.mor.praak.validation.required': 'Opplysningen er påkrevd',
    'skjema.mor.confirm.title': 'Bekreft opplysninger om faren til barnet',
    'skjema.mor.confirm.farCorrect.label': 'Jeg godkjenner at opplysningene om faren til barnet er korrekt.',
    'skjema.mor.confirm.cannotWithdraw.label': 'Jeg er klar over at jeg ikke kan trekke tilbake denne bekreftelsen senere.',
    'skjema.confirm.signeringPostenInfo': 'Du blir videresendt til Posten sin løsning for signering',

    'skjema.far.borSammen.title': 'Bor du sammen med moren til barnet?',
    'skjema.far.lesOpplysninger.title': 'Les opplysninger oppgitt av moren til barnet',
    'skjema.far.confirm.title': 'Signer farskapserklæringen',
    'skjema.far.confirm.readAndUnderstood.label': 'Jeg har lest og forstått hva farksapserklæringen innebærer.',
    'skjema.far.confirm.cannotWithdraw.label': 'Jeg er kjent med at denne bekreftelsen ikke kan trekkes tilbake på et senere tidspunkt.',

    'kvittering.intro.foedselsnummer': 'med fødselsnummer {fnr}.',
    'kvittering.intro.termindato': 'forventet født {termindato}.',
    'kvittering.intro.downloadPdfNotSigned': 'Du kan laste ned farskapserklæringen som en pdf på denne siden etter at begge parter har signert.',
    'kvittering.intro.downloadPdf': 'Last ned ferdig signert farskapserklæring som pdf her: ',
    'kvittering.intro.pdfName': 'Farskapserklæring.pdf',
    'kvittering.intro.mor.1': 'Vi har mottatt dine opplysninger om far {date}.',
    'kvittering.intro.mor.2': 'Erklæringen vil bli videresendt til han for godkjenning og signering.',
    'kvittering.intro.mor.3': 'Du kan ikke endre opplysningene du har gitt.',
    'kvittering.intro.mor.4': 'Du kan finne igjen erklæringene her: ',
    'kvittering.intro.mor.farSignert': 'Far har {date} erklært farskap for barn',

    'kvittering.intro.far.1': 'Du har signert farskapserklæring {date} for barn',
    'kvittering.intro.far.2': 'Erklæringen er endelig og kan ikke endres.',
    'kvittering.intro.far.3': 'Du kan finne igjen erklæringer her: ',
    'kvittering.morAlert.1': 'Erklæringen er ikke gyldig før oppgitt far har signert.',
    'kvittering.morAlert.2': 'Han kan allerede nå logge seg inn på Ditt NAV og signere erklæringen. Vi vil også sende ham en påminnelse på e-post og/eller sms. (OBS! Brukernotifikasjoner dukker ikke opp under pilottesten nå, far må også logge inn på farskapsportal.nav.no)',
    'kvittering.prosessIndikator.step.1': '1. Mor oppgir far',
    'kvittering.prosessIndikator.step.2': '2. Far erklærer farskap',
    'kvittering.prosessIndikator.step.3': '3. Erklæringen oversendes folkeregisteret for registering og arkivering',
    'kvittering.hvaSkjerVidere.title': 'Hva skjer videre?',
    'kvittering.hvaSkjerVidere.1': 'Det er Skatteetaten ved Folkeregisteret som har ansvaret for å registrere og arkivere farskapserklæringer. Dere vil få oversendt erklæringen når dere begge har signert den. Etter at dere har valgt navnet til barnet vil du motta en bekreftelse på registrering av fødselsnummer og navn. Bekreftelsen mottar du i innboksen din i Altinn.',
    'kvittering.hvaSkjerVidere.2': 'Flere opplysninger finner du her:',
    'kvittering.hvaSkjerVidere.link': 'https://www.skatteetaten.no/person/folkeregister/fodsel-og-navnevalg',
    'kvittering.hvaSkjerHvis.title': 'Hva skjer hvis?',
    'kvittering.hvaSkjerHvis.farSignererIkke.title': 'Faren du har oppgitt ikke signerer erklæringen',
    'kvittering.hvaSkjerHvis.farSignererIkke.termindato.text': 'Hvis faren du har oppgitt ikke har signert erklæringen innen en måned etter fødselen, vil vi kontakte deg for å fastsette farskapet. Hvis faren til barnet glemmer å signere erklæringen ber vi om at du minner ham på dette.',
    'kvittering.hvaSkjerHvis.farSignererIkke.foedselsnummer.text': 'Hvis oppgitt far ikke signerer erklæringen innen en måned, vil du bli kontaktet av NAV for å få farskapet fastsatt. Hvis far har glemt å signere erklæringen ber vi om at du minner han på dette.',
    'kvittering.hvaSkjerHvis.foedtIUtlandet.title': 'Barnet blir født i utlandet',
    'kvittering.hvaSkjerHvis.foedtIUtlandet.text': 'Den elektroniske erklæringen er ikke gyldig hvis barnet blir født i utlandet. Hvis dette skjer, må dere erklære farskapet på nytt på papir.',
    'kvittering.hvaSkjerHvis.barnetDoer.title': 'Barnet dør',
    'kvittering.hvaSkjerHvis.barnetDoer.text': 'Hvis barnet dør før svangerskapet er fullgått, vil farskapet i enkelte tilfeller likevel bli registrert. Vi ber deg kontakte Skatteetaten hvis du har spørsmål om dette.',
    'kvittering.ytelserOgTjenester.title': 'Relaterte ytelser og tjenester fra NAV',
    'kvittering.ytelserOgTjenester.foreldrepengerSvangerskapspengerEngangsstoenad.title': 'Foreldrepenger, svangerskapspenger og engangsstønad',
    'kvittering.ytelserOgTjenester.foreldrepengerSvangerskapspengerEngangsstoenad.text': 'Du finner informasjon om hvilke rettigheter du har og søknadsskjema her:',
    'kvittering.ytelserOgTjenester.foreldrepengerSvangerskapspengerEngangsstoenad.link': 'https://familie.nav.no',
    'kvittering.ytelserOgTjenester.barnetrygd.title': 'Barnetrygd',
    'kvittering.ytelserOgTjenester.barnetrygd.text': 'Du trenger som hovedregel ikke å søke om barnetrygd. Hvis barnet blir født i Norge, vil moren til barnet automatisk få barnetrygd omtrent 2 måneder etter fødselen. Du finner mer informasjon om retten til barnetrygd her:',
    'kvittering.ytelserOgTjenester.barnetrygd.link': 'https://www.nav.no/no/person/familie/barnetrygd-og-kontantstotte/barnetrygd#chapter-1',
    'kvittering.ytelserOgTjenester.utvidetBarnetrygd.title': 'Utvidet barnetrygd',
    'kvittering.ytelserOgTjenester.utvidetBarnetrygd.text': 'Hvis du er enslig mor eller far kan du søke om utvidet barnetrygd. Du finner mer informasjon her:',
    'kvittering.ytelserOgTjenester.utvidetBarnetrygd.link': 'https://www.nav.no/no/person/familie/barnetrygd-og-kontantstotte/barnetrygd#chapter-1',
    'kvittering.ytelserOgTjenester.barnebidrag.title': 'Barnebidrag',
    'kvittering.ytelserOgTjenester.barnebidrag.text': 'Hvis du ikke bor sammen med den andre forelderen kan du ha rett til barnebidrag. Du finner mer informasjon her:',
    'kvittering.ytelserOgTjenester.barnebidrag.link': 'https://www.nav.no/no/person/familie/barnetrygd-og-kontantstotte/barnetrygd#chapter-1',
    'kvittering.ytelserOgTjenester.stoenadTilEnsligMorEllerFar.title': 'Stønad til enslig mor eller far',
    'kvittering.ytelserOgTjenester.stoenadTilEnsligMorEllerFar.text': 'Hvis du er alene med barn finnes det ulike støtteordninger du kan ha rett til. Du finner mer informasjon her:',
    'kvittering.ytelserOgTjenester.stoenadTilEnsligMorEllerFar.link': 'https://www.nav.no/familie/alene-med-barn',

    'signer.alert.1': 'Du har fylt ut opplysninger om far og barn, men har ikke signert skjema. Sjekk om opplysningene stemmer og signer skjemaet.',
    'signer.alert.2': 'Vil du slette eller endre erklæringen, ta kontakt med NAV på nav.no/kontakt eller telefon 55 55 33 33.',
    'signer.submit': 'Signer',
    'signer.cancel': 'Avbryt',

    'avbrutt.alert.mor': 'Du har avbrutt signeringen og den påbegynte erklæringen er slettet. For å opprette en ny farskapserklæringen, må du starte prosesen på nytt.',
    'avbrutt.alert.far': 'Du har avbrutt signeringen og den påbegynte erklæringen er slettet. For å opprette en ny farskapserklæringen, må moren til barnet starte prosesen på nytt.',
}
