/* eslint-disable */
export default {
    'two': 'to',
    'three': 'tre',
    'foedselsnummer': 'Fødselsnummer',
    'termindato': 'Termindato',
    'navn': 'Navn',
    'mor': 'Mor',
    'far': 'Far',
    'farskapserklaering': 'Farskapserklæring',

    'api.error': 'Oisann, noe gikk galt!',

    'form.feiloppsummering': 'For å gå videre må du rette opp følgende:',
    'form.date.placeholder': 'dd.mm.åååå',

    'error.taKontakt': 'Ta gjerne kontakt med oss på telefon 55 55 33 33 for å få informasjon om hvordan du skal gå frem for å få fastsatt farskap.',

    'withUserInfoError.banner.title': 'Oops,',
    'withUserInfoError.banner.text': 'noe gikk galt.',
    'withUserInfoError.title': 'Det oppstod en feil ved henting av brukerinformasjon',
    'withUserInfoError.text': 'Vennligst prøv igjen senere.',

    'breadcrumbs.forside': 'Farskapserklæring',
    'breadcrumbs.oversikt': 'Dine farskapserklæringer',
    'breadcrumbs.skjema': 'Opprett farskapserklæring',
    'breadcrumbs.kvittering': 'Bekreftelse på innsendt farskapserklæring',
    'breadcrumbs.signer': 'Signer farskapserklæring',

    'header.forside': 'Farskapserklæring',
    'header.oversikt': 'Dine farskapserklæringer',
    'header.skjema': 'Opprett farskapserklæring',
    'header.kvittering': 'Bekreftelse på innsendt farskapserklæring',
    'header.signer': 'Signer farskapserklæring',

    'farskapserklaering.aboutChildren': 'Gjelder barn',
    'farskapserklaering.expectingChildren': 'Venter barn',
    'farskapserklaering.bornChildren': 'Født(e) barn',
    'farskapserklaering.parents': 'Foreldre',
    'farskapserklaering.borSammen': 'Bor sammen',
    'farskapserklaering.borSammen.yes': 'Ja',
    'farskapserklaering.borSammen.no': 'Nei',

    'forside.innebaerer.title': 'Hva innebærer det å erklære farskap?',
    'forside.innebaerer.description': 'Når barnets foreldre ikke er gift med hverandre, følger ikke farskapet direkte av loven. Det vanlige i slike tilfeller er at farskap etableres ved at mor oppgir hvem som er far, og han erklærer farskapet. Farskap kan erklæres digitalt ved at begge foreldrene identifiserer seg elektronisk på en sikker måte og signerer en digital erklæring. Å erklære farskap for et barn gir far både rettigheter og plikter ovenfor barnet, som for eksempel:',
    'forside.innebaerer.foreldreansvar.title': 'Foreldreansvar',
    'forside.innebaerer.foreldreansvar.content.1': 'Foreldreansvar er den rett og plikt foreldre har til å bestemme over barnet i personlige forhold. Foreldre skal utøve foreldreansvaret ut fra barnets behov og interesser. Den eller de som har foreldreansvar, er også barnets verge.',
    'forside.innebaerer.foreldreansvar.content.2': 'For barn som blir født etter 1. januar 2020 får mor og far felles foreldreansvar. Dette gjelder barn som har gifte foreldre, barn som har samboende foreldre og barn som har foreldre som ikke bor sammen.',
    'forside.innebaerer.foreldreansvar.content.3': 'Dersom mor ønsker å ha foreldreansvaret alene må hun melde fra til Folkeregisteret om det innen ett år fra den dagen farskapet er fastsatt. Dersom far ikke ønsker å ha foreldreansvar må han melde fra til Folkeregisteret om det innen ett år fra den dagen farskapet er fastsatt. Dersom mor har meldt inn at hun ønsker foreldreansvaret alene og far ønsker foreldreansvaret eller delt foreldreansvar må han selv ta saken til domstolen.',
    'forside.innebaerer.barnebidrag.title': 'Barnebidrag',
    'forside.innebaerer.barnebidrag.content': 'Begge foreldrene har plikt til å sørge for underholdet av barnet sitt etter evne. Når foreldrene ikke bor sammen, må den som ikke bor fast sammen med barnet betale barnebidrag. Foreldrene kan inngå avtale om barnebidragets størrelse. Dersom foreldrene ikke blir enige, kan hver av dem kreve at NAV fastsetter størrelsen på barnebidraget. Dersom foreldrene ikke lever sammen når barnet blir født, og de ikke har gjort avtale om bidraget, skal NAV av eget tiltak fastsette bidrag til barnet.',
    'forside.innebaerer.samvaer.title': 'Samvær',
    'forside.innebaerer.samvaer.content.1': 'Barnet har rett til samvær med begge foreldrene selv om de lever hver for seg. Foreldrene har gjensidig ansvar for at samværsretten blir oppfylt.',
    'forside.innebaerer.samvaer.content.2': 'En avtale om foreldreansvar, samvær eller hvor barnet skal bo fast, kan endres ved ny avtale mellom foreldrene. Dersom foreldrene ikke blir enige, kan de bringe saken inn for retten.',
    'forside.innebaerer.arv.title': 'Arv',
    'forside.innebaerer.arv.content': 'Når farskapet er gyldig fastsatt, har barnet arverett etter far.',
    'forside.innebaerer.navn.title': 'Navn',
    'forside.innebaerer.navn.content': 'Foreldre med foreldreansvar velger navn til barnet. De må sende melding om navnevalget til Folkeregisteret. Hvis foreldrene ikke gir melding om etternavn innen 6 måneder, får barnet morens etternavn.',

    'forside.naar.title': 'Når kan farskap erklæres?',
    'forside.naar.content.1': 'Farskap kan erklæres digitalt både før og etter barnets fødsel.',
    'forside.naar.content.2': 'Farskap kan tidligst erklæres når mor er i 22. svangerskapsuke.',

    'forside.elektroniskNaar.title': 'Farskap kan erklæres elektronisk når',
    'forside.elektroniskNaar.content.1': 'Barnet er født, ventes født i Norge.',
    'forside.elektroniskNaar.content.2': 'Mor er bosatt i Norge.',
    'forside.elektroniskNaar.content.3': 'Begge foreldrene har norsk fødsels- og personnummer.',
    'forside.elektroniskNaar.content.4': 'Begge foreldrene er over 18 år.',
    'forside.elektroniskNaar.content.5': 'Mor er minst 21 uker på vei eller barnet er allerede født.',

    'forside.hvordan.title': 'Hvordan erklære farskap elektronisk',
    'forside.hvordan.foer.title': 'Før fødsel',
    'forside.hvordan.foer.step.1.title': 'Mor oppgir far.',
    'forside.hvordan.foer.step.1.content.1': 'Mor logger inn i løsningen for farskapserklæring.',
    'forside.hvordan.foer.step.1.content.2': 'Mor oppgir termindato.',
    'forside.hvordan.foer.step.1.content.3': 'Mor oppgir fars navn og fødselsnummer (11 siffer).',
    'forside.hvordan.foer.step.1.content.4': 'Mor bekrefter at oppgitt person er barnets far.',
    'forside.hvordan.foer.step.2.title': 'Far erklærer farskap.',
    'forside.hvordan.foer.step.2.content.1': 'Far får melding fra mor eller NAV med lenke til løsningen.',
    'forside.hvordan.foer.step.2.content.2': 'Far logger inn og kontrollerer opplysningene.',
    'forside.hvordan.foer.step.2.content.3': 'Far bekrefter at han er kjent med rettsvirkningene av å erklære farskap.',
    'forside.hvordan.foer.step.2.content.4': 'Far signerer erklæringen.',
    'forside.hvordan.foer.step.3.title': 'Erklæringen oversendes Folkeregisteret for registrering og arkivering.',
    'forside.hvordan.etter.title': 'Etter fødsel',
    'forside.hvordan.etter.step.1.title': 'Mor oppgir far.',
    'forside.hvordan.etter.step.1.content.1': 'Mor logger inn i løsningen for farskapserklæring.',
    'forside.hvordan.etter.step.1.content.2': 'Mor velger barn hun vil oppgi far til.',
    'forside.hvordan.etter.step.1.content.3': 'Mor oppgir fars navn og fødselsnummer (11 siffer).',
    'forside.hvordan.etter.step.1.content.4': 'Mor bekrefter at oppgitt person er barnets far.',
    'forside.hvordan.etter.step.2.title': 'Far erklærer farskap.',
    'forside.hvordan.etter.step.2.content.1': 'Far får melding fra mor eller NAV med lenke til løsningen.',
    'forside.hvordan.etter.step.2.content.2': 'Far logger inn og kontrollerer opplysningene.',
    'forside.hvordan.etter.step.2.content.3': 'Far bekrefter at han er kjent med rettsvirkningene av å erklære farskap.',
    'forside.hvordan.etter.step.2.content.4': 'Far signerer erklæringen.',
    'forside.hvordan.etter.step.3.title': 'Erklæringen oversendes Folkeregisteret for registrering og arkivering.',

    'forside.oppmoeteLink.title': 'Erklære farskapet gjennom oppmøte',
    'forside.oppmoeteLink.content': 'Hvis dere ikke oppfyller vilkårene for å erklære farskap elektronisk kan dere kontakte NAV for å få informasjon om hvilke andre muligheter dere har.',

    'forside.loginButton': 'Fyll ut erklæring om farskap',

    'notPermitted.ikkeMyndig': 'For at farskap skal kunne erklæres elektronisk, må begge foreldrene være over 18 år.',
    'notPermitted.medmorEllerUkjent': 'Medmor eller person med ukjent rolle kan ikke benytte løsningen', // TODO: endre tekst
    'notPermitted.morSivilstandGift.1': 'Du er gift og ektefellen din blir automatisk registrert som far til barn du føder.',
    'notPermitted.morSivilstandGift.2': 'Hvis det er en annen mann enn ektefellen din som er barnets far, kan farskapet endres. Dette kan ikke gjøres elektronisk. Du finner mer informasjon om endring av farskap <a>her</a>. Du er også velkommen til å kontakte oss på telefon 55 55 33 33.',
    'notPermitted.morSivilstandGift.link': 'https://www.nav.no/no/person/familie/farskap-og-morskap',
    'notPermitted.morSivilstandPartner.1': 'Du er gift/registrert partner og du og ektefellen/partneren din må sende en søknad til Skatteetaten for å få medmorskap registret.',
    'notPermitted.morSivilstandPartner.2': 'Du finner informasjon og søknadsskjema <a>her</a>.',
    'notPermitted.morSivilstandPartner.link': 'https://www.skatteetaten.no/person/folkeregister/fodsel-og-navnevalg/soknad-om-medmorskap/',
    'notPermitted.morSivilstandUoppgitt': 'Du har uoppgitt sivilstand og kan ikke opprette farskapserklæring', // TODO: endre tekst

    'oversikt.infoPanel.greeting': 'Hei!',

    'oversikt.infoPanel.common.forBarn.termindato': 'forventet født {termindato}',
    'oversikt.infoPanel.common.forBarn.foedselsnummer': 'med fødselsnummer {fnr}',

    'oversikt.infoPanel.mor.utenBarn.1': 'Hvis du er minimum 20 uker på vei kan du oppgi termindato og gi opplysninger om far slik at han kan erklære farskapet elektronisk.',
    'oversikt.infoPanel.mor.utenBarn.2': 'Du må ha fullt navn og fødselsnummer på mannen du oppgir som far.',
    'oversikt.infoPanel.mor.medBarn.1.single': 'Vi har fått opplysninger om ditt nylig født barn:',
    'oversikt.infoPanel.mor.medBarn.1.multiple': 'Vi har fått opplysninger om dine nylige fødte barn:',
    'oversikt.infoPanel.mor.medBarn.2': 'Ifølge våre opplysninger er farskap ikke fastsatt for ovennevnte barn. Hvis du gir opplysninger om far nedenfor, kan han erklære farskap elektronisk. Husk at du må ha fullt navn og fødselsnummer på mannen du oppgir som far.',
    'oversikt.infoPanel.mor.ikkeSignert.1': 'Du har påbegynt erklæring for barn',
    'oversikt.infoPanel.mor.ikkeSignert.2': 'Hvis opplysningene du har gitt om far ikke stemmer, eller du er usikker på hvem som er barnets far, kan du slette erklæringen ved å ta kontakt med NAV på telefon 55 55 33 33.',
    'oversikt.infoPanel.mor.farIkkeSignert.1': 'Du har tidligere gitt opplysninger om far til barn',
    'oversikt.infoPanel.mor.farIkkeSignert.2': 'Oppgitt far har ikke erklært farskap for barnet. Når han erklærer farskapet, blir erklæringen oversendt til Skatteetaten for registrering. En kopi av erklæringen blir også sendt til adressen du har registret hos NAV.',
    'oversikt.infoPanel.mor.farSignert.1': 'Du har gitt opplysninger om far til barn',
    'oversikt.infoPanel.mor.farSignert.2': 'og oppgitt far har erklært farskap for barnet.',
    'oversikt.infoPanel.mor.farSignert.3': 'Erklæringen er oversendt til Skatteetaten for registrering. En kopi av erklæringen er sendt til e-post du har registret hos NAV.',

    'oversikt.infoPanel.far.utenErklaering': 'Det er ingen farskapserklæring som venter på din signatur. For at farskap skal kunne erklæres elektronisk må mor først oppgi deg som far.',
    'oversikt.infoPanel.far.ikkeSignert': 'Du er oppgitt som far til barn.', // TODO
    'oversikt.infoPanel.far.signert': 'Du har erklært farskap og erklæringen er oversendt til Folkeregisteret for registrering. En kopi av erklæringen er også sendt til adressen du har registret hos NAV.', // TODO

    'oversikt.moreInfoPanels.erFarskapRegistrert.title': 'Er du usikker på om farskap for et barn er registrert?',
    'oversikt.moreInfoPanels.erFarskapRegistrert.content': 'Hvis du allerede har født et barn og lurer på om farskap er registrert ber vi deg ta kontakt med Skatteetaten. Du finner mer informasjon om registrering av farskap <a>her</a>. Hvis du tidligere har erklært farskap elektronisk skal erklæringen ha blitt sendt til e-postadressen du har registrert hos NAV.',
    'oversikt.moreInfoPanels.erFarskapRegistrert.link': 'https://www.skatteetaten.no/person/folkeregister/fodsel-og-navnevalg/barn-fodt-i-norge/',
    'oversikt.moreInfoPanels.hvemErFar.title': 'Er du usikker på hvem som er barnets far?',
    'oversikt.moreInfoPanels.hvemErFar.content': 'Hvis du ikke har fullt navn og fødselsnummer eller er usikker på hvem som er barnets far kan du ikke bruke løsningen. Hvis farskap ikke er fastsatt når barnet blir født vil du bli kontaktet for å få fastsatt farskapet. Hvis du lurer på saksgang eller annet, kan du kontakte oss på telefon 55 55 33 33.',
    'oversikt.moreInfoPanels.medmor.title': 'Ønsker du å oppgi medmor?',
    'oversikt.moreInfoPanels.medmor.content.1': 'En medmor er en kvinne som har fått juridisk foreldrestatus for det biologiske barnet til sin kvinnelige ektefelle eller samboer. Hvis du er samboer med en kvinne, kan dere søke om medmorskap hvis barnet har blitt til ved hjelp av assistert befruktning.',
    'oversikt.moreInfoPanels.medmor.content.2': 'Du finner informasjon og søknadsskjema <a>her</a>.',
    'oversikt.moreInfoPanels.medmor.content.link': 'https://www.skatteetaten.no/person/folkeregister/fodsel-og-navnevalg/soknad-om-medmorskap/',
    'oversikt.moreInfoPanels.hvaSkjerNaa.title': 'Hva skjer nå?',
    'oversikt.moreInfoPanels.hvaSkjerNaa.content': 'Det er Skatteetaten ved Folkeregisteret som er ansvarlig for å registrere og arkivere farskapserklæringer. Når dere melder inn opplysninger om barnets navn til dem vil du motta en bekreftelse på registrering av fødselsnummer og navn. Bekreftelsen mottar du i din innboks i Altinn. Du finner mer informasjon om registrering av farskap og navnevalg <a>her</a>.',
    'oversikt.moreInfoPanels.hvaSkjerNaa.link': 'https://www.skatteetaten.no/person/folkeregister/fodsel-og-navnevalg/barn-fodt-i-norge/',
    'oversikt.moreInfoPanels.farErklaererIkke.title': 'Hva skjer hvis far ikke erklærer farskapet?',
    'oversikt.moreInfoPanels.farErklaererIkke.content': 'Hvis oppgitt far ikke erklærer farskap har NAV ansvar for å få fastsatt dette. Det kan da være aktuelt med innkalling av mulige parter og bekreftelse av farskapet ved bruk av DNA-analyse. Du finner ytterligere informasjon på nav.no eller du kan kontakte oss på telefon 55 55 33 33.',
    'oversikt.moreInfoPanels.erklaereUtenMor.title': 'Vil du erklære farskap for et barn uten at mor har oppgitt deg som far?',
    'oversikt.moreInfoPanels.erklaereUtenMor.content.1': 'Hvis du ønsker å erklære farskap for et barn og ikke har blitt oppgitt som far kan du møte personlig, samt forevise legitimasjon for en av disse instansene:',
    'oversikt.moreInfoPanels.erklaereUtenMor.content.li.1': 'Lege/jordmor i forbindelse med svangerskapskontroll/fødsel',
    'oversikt.moreInfoPanels.erklaereUtenMor.content.li.2': 'Skattekontor',
    'oversikt.moreInfoPanels.erklaereUtenMor.content.li.3': 'NAV-kontor',
    'oversikt.moreInfoPanels.erklaereUtenMor.content.li.4': 'Dommer',
    'oversikt.moreInfoPanels.erklaereUtenMor.content.li.5': 'Norsk diplomatisk eller konsulær tjenestemann, dersom faren er i utlandet',
    'oversikt.moreInfoPanels.erklaereUtenMor.content.2': 'For mer informasjon se informasjon om <a>her</a> eller kontakt oss på telefon 55 55 33 33.',
    'oversikt.moreInfoPanels.erklaereUtenMor.content.2.link': '', // TODO
    'oversikt.moreInfoPanels.alleredeErklaert.title': 'Har du allerede erklært farskap og lurer på hva som skjer nå?',
    'oversikt.moreInfoPanels.alleredeErklaert.content.1': 'Det er Skatteetaten ved Folkeregisteret som er ansvarlig for å registrere og arkivere farskapserklæringer. Når dere melder inn opplysninger om barnets navn til dem vil du motta en bekreftelse på registrering av fødselsnummer og navn. Bekreftelsen mottar du i din innboks i Altinn.',
    'oversikt.moreInfoPanels.alleredeErklaert.content.2': ' Du finner mer informasjon om registrering av farskap og navnevalg <a>her</a>.',
    'oversikt.moreInfoPanels.alleredeErklaert.link': 'https://www.skatteetaten.no/person/folkeregister/fodsel-og-navnevalg/barn-fodt-i-norge/',
    'oversikt.moreInfoPanels.erJegFar.title': 'Hva gjør jeg hvis jeg er usikker på om jeg er far til barnet?',
    'oversikt.moreInfoPanels.erJegFar.content': 'Hvis du erklærer farskap for barnet kan du ikke senere trekke erklæringen tilbake. Hvis du er usikker på om du er barnets far bør du derfor ikke signere erklæringen. NAV vil da ta ansvar for at farskap blir fastsatt. Du kan i så fall bli innkalt og bedt om å gi prøve til DNA-analyse. Du finner ytterligere informasjon på nav.no eller du kan kontakte oss på telefon 55 55 33 33.',

    'oversikt.barn.link.title': 'Opprett farskapserklæring for barn',
    'oversikt.barn.link.status': 'Dette barnet har ikke en registrert far i Folkeregisteret',

    'oversikt.erklaeringer.link.forelder.mor': 'fra ',
    'oversikt.erklaeringer.link.forelder.far': 'med ',
    'oversikt.erklaeringer.link.status.signering-bruker': 'Venter på din signering',
    'oversikt.erklaeringer.link.status.signering-motpart': 'Venter på motparts signering',
    'oversikt.erklaeringer.link.status.registrering': 'Signert og sendt til Folkeregisteret',
    'oversikt.goToSkjemaButton': 'Opprett farskapserklæring',

    'skjema.next': 'Neste',
    'skjema.cancel': 'Avbryt',
    'skjema.edit': 'Endre',
    'skjema.submit': 'Signer farskapserklæring',

    'skjema.borSammen.description': 'Foreldre som ikke bor sammen med barnet har plikt til å betale bidrag.',
    'skjema.borSammen.label.yes': 'Ja',
    'skjema.borSammen.label.no': 'Nei',
    'skjema.borSammen.validation.required': 'Opplysningen er påkrevd',

    'skjema.confirm.validation.required': 'Du må bekrefte før søknaden kan sendes inn.',

    'skjema.mor.barn.title': 'Gjelder barn(a)',
    'skjema.mor.barn.description': 'Legg inn termindatoen slik den er beregnet i ultralydundersøkelsen. Hvis du har fått en dato for planlagt keisersnitt, legger du inn denne datoen som termindato.',
    'skjema.mor.barn.termindato.validation.required': 'Termindato er påkrevd',
    'skjema.mor.barn.termindato.validation.pattern': 'Ugyldig dato',
    'skjema.mor.barn.termindato.validation.minDate': 'Kan ikke være mer enn tre uker tilbake i tid',
    'skjema.mor.barn.termindato.validation.maxDate': 'Datoen er mer enn 40 uker fram i tid. Vent til uke 22 av svangerskapet med å bekrefte far.',
    'skjema.mor.barn.termindato.validation.beforeWeek22': 'Du er i uke {weekNr} i svangerskapet. Vent til uke 22 med å bekrefte far.',
    'skjema.mor.far.title': 'Far til barn(a)',
    'skjema.mor.far.navn.label': 'Navn til far',
    'skjema.mor.far.navn.description.1': 'Oppgi fullt navn slik det står i Folkeregisteret',
    'skjema.mor.far.navn.description.2': 'Skriv navnet slik: fornavn mellomnavn etternavn.',
    'skjema.mor.far.navn.validation.required': 'Navn til far er påkrevd',
    'skjema.mor.far.foedselsnummer.label': 'Fødselsnummer til far (11 siffer)',
    'skjema.mor.far.foedselsnummer.validation.required': 'Fødselsnummer er påkrevd',
    'skjema.mor.far.foedselsnummer.validation.fnr': 'Ugyldig fødselsnummer',
    'skjema.mor.far.validation.feilRolleFar.1': 'Medmorskap kan ikke erklæres elektronisk. Hvis du er samboer med en kvinne, kan dere søke Skatteetaten om medmorskap hvis barnet har blitt til ved hjelp av assistert befruktning.',
    'skjema.mor.far.validation.feilRolleFar.2': 'Du finner informasjon og søknadsskjema <a>her</a>',
    'skjema.mor.far.validation.feilRolleFar.link': 'https://www.skatteetaten.no/person/folkeregister/fodsel-og-navnevalg/soknad-om-medmorskap/',
    'skjema.mor.far.validation.forskjelligeFedre': 'Du kan ikke opprette farskapserklæringer med forskjellige fedre for samme kull nyfødte', // TODO: skal denne kunne oppstå? Kanskje ikke tillate mor å taste inn annen far?
    'skjema.mor.far.validation.ikkeMyndig': 'Oppgitt far er ikke myndig. For at farskap skal kunne erklæres elektronisk, må begge foreldrene være over 18 år.',
    'skjema.mor.far.validation.maksAntallForsoek.1': 'Du har tastet feil fødselsnummer/navn på oppgitt far fem ganger og har nå blitt blokkert fra løsningen.',
    'skjema.mor.far.validation.maksAntallForsoek.2': 'Du kan prøve på nytt i morgen.',
    'skjema.mor.far.validation.navnStemmerIkkeMedRegister.1': 'Navn til far og fødselsnummer til far gir feil.',
    'skjema.mor.far.validation.navnStemmerIkkeMedRegister.2': 'Sjekk at navnet er stavet riktig og fødselsnummer stemmer.',
    'skjema.mor.far.validation.resterendeForsoek': 'Du har tastet feil fødselsnummer/navn på oppgitt far {incorrectAttempts} ganger. Vennligst be far sjekke hvordan navnet hans er skrevet i Folkeregisteret før du prøver på nytt. Hvis du taster feil fem ganger vil du bli blokkert fra løsningen.',
    'skjema.mor.far.validation.resterendeForsoek.final': 'Du har tastet feil fødselsnummer/navn på oppgitt far fire ganger og har bare ett forsøk igjen før du vil bli blokkert fra løsningen.',
    'skjema.mor.borSammen.title': 'Bor du sammen med far?',
    'skjema.mor.confirm.title': 'Bekreft opplysninger om far',
    'skjema.mor.confirm.farCorrect.label': 'Jeg godkjenner at opplysningene om far er korrekt.',
    'skjema.mor.confirm.cannotWithdraw.label': 'Jeg er kjent med at denne bekreftelsen ikke kan trekkes tilbake på et senere tidspunkt.',

    'skjema.far.borSammen.title': 'Bor du sammen med mor?',
    'skjema.far.lesOpplysninger.title': 'Les opplysninger oppgitt av mor',
    'skjema.far.confirm.title': 'Signer farskapserklæring',
    'skjema.far.confirm.readAndUnderstood.label': 'Jeg har lest og forstått hva farksapserklæringen innebærer.',
    'skjema.far.confirm.cannotWithdraw.label': 'Jeg er kjent med at denne bekreftelsen ikke kan trekkes tilbake på et senere tidspunkt.',

    'kvittering.intro.foedselsnummer': 'med fødselsnummer {fnr}.',
    'kvittering.intro.termindato': 'forventet født {termindato}.',
    'kvittering.intro.mor.1': 'Vi har mottatt dine opplysninger om far {date}.',
    'kvittering.intro.mor.2': 'Erklæringen vil bli videresendt til han for godkjenning og signering.',
    'kvittering.intro.mor.3': 'Du kan ikke endre opplysningene du har gitt.',
    'kvittering.intro.mor.4': 'Du kan gjenfinne erklæringene her:',
    'kvittering.intro.mor.link': '[lenke]', // TODO
    'kvittering.intro.mor.farSignert': 'Far har {date} erklært farskap for barn',

    'kvittering.intro.far.1': 'Du har signert farskapserklæring {date} for barn',
    'kvittering.intro.far.2': 'Erklæringen er endelig og kan ikke endres.',
    'kvittering.intro.far.3': 'Du kan gjenfinne erklæringer her:',
    'kvittering.intro.far.link': '[lenke]', // TODO
    'kvittering.morAlert': 'Erklæringen er ikke gyldig før oppgitt far har signert. Han kan allerede nå logge seg inn på dittnav og signere erklæringen. Du bør gjøre han oppmerksom på dette. Hvis ikke far har signert etter tre dager vil vi sende han en påminnelse per sms.',
    'kvittering.hvaSkjerVidere.title': 'Hva skjer videre?',
    'kvittering.hvaSkjerVidere.1': 'Det er Skatteetaten ved Folkeregisteret som har ansvar for å registrere og arkivere farskapserklæringer. Når erklæringen er signert av dere begge vil den derfor bli oversendt til dem. Etter at dere har valgt navn til barnet vil du motta en bekreftelse på registrering av fødselsnummer og navn. Bekreftelsen mottar du i din innboks i Altinn.',
    'kvittering.hvaSkjerVidere.2': 'Mer opplysninger finner du her:',
    'kvittering.hvaSkjerVidere.link': 'https://www.skatteetaten.no/person/folkeregister/fodsel-og-navnevalg',
    'kvittering.hvaSkjerHvis.title': 'Hva skjer hvis?',
    'kvittering.hvaSkjerHvis.farSignererIkke.title': 'Oppgitt far ikke signerer erklæringen',
    'kvittering.hvaSkjerHvis.farSignererIkke.termindato.text': 'Hvis oppgitt far ikke har signert erklæringen innen en måned etter fødsel, vil du bli kontaktet av NAV for å få farskapet fastsatt. Hvis far glemmer å signere erklæringen ber vi om at du minner han på dette.',
    'kvittering.hvaSkjerHvis.farSignererIkke.foedselsnummer.text': 'Hvis oppgitt far ikke signerer erklæringen innen en måned, vil du bli kontaktet av NAV for å få farskapet fastsatt. Hvis far har glemt å signere erklæringen ber vi om at du minner han på dette.',
    'kvittering.hvaSkjerHvis.foedtIUtlandet.title': 'Barnet blir født i utlandet',
    'kvittering.hvaSkjerHvis.foedtIUtlandet.text': 'Den elektroniske erklæringen er ikke gyldig hvis barnet blir født i utlandet. Hvis dette skjer, må farskap erklæres på nytt på papir.',
    'kvittering.hvaSkjerHvis.barnetDoer.title': 'Barnet dør',
    'kvittering.hvaSkjerHvis.barnetDoer.text': 'Hvis barnet dør før svangerskapet er fullgått, vil farskapet i enkelte tilfeller likevel bli registrert. Vi ber deg kontakte Skatteetaten hvis du har utfyllende spørsmål omkring dette.',
    'kvittering.ytelserOgTjenester.title': 'Relaterte ytelser og tjenester fra NAV',
    'kvittering.ytelserOgTjenester.foreldrepengerSvangerskapspengerEngangsstoenad.title': 'Foreldrepenger, svangerskapspenger og engangsstønad',
    'kvittering.ytelserOgTjenester.foreldrepengerSvangerskapspengerEngangsstoenad.text': 'Du finner informasjon om hvilke rettigheter du har og søknadsskjema her:',
    'kvittering.ytelserOgTjenester.foreldrepengerSvangerskapspengerEngangsstoenad.link': 'https://familie.nav.no',
    'kvittering.ytelserOgTjenester.barnetrygd.title': 'Barnetrygd',
    'kvittering.ytelserOgTjenester.barnetrygd.text': 'Du trenger som hovedregel ikke å søke om barnetrygd. Hvis barnet blir født i Norge, vil mor automatisk få barnetrygd omtrent 2 måneder etter fødselen. Du finner mer informasjon om retten til barnetrygd her:',
    'kvittering.ytelserOgTjenester.barnetrygd.link': 'https://www.nav.no/no/person/familie/barnetrygd-og-kontantstotte/barnetrygd#chapter-1',
    'kvittering.ytelserOgTjenester.utvidetBarnetrygd.title': 'Utvidet barnetrygd',
    'kvittering.ytelserOgTjenester.utvidetBarnetrygd.text': 'Hvis du er enslig mor eller far kan du søke om utvidet barnetrygd. Du finner mer informasjon her:',
    'kvittering.ytelserOgTjenester.utvidetBarnetrygd.link': 'https://www.nav.no/no/person/familie/barnetrygd-og-kontantstotte/barnetrygd#chapter-1',
    'kvittering.ytelserOgTjenester.barnebidrag.title': 'Barnebidrag',
    'kvittering.ytelserOgTjenester.barnebidrag.text': 'Hvis du ikke bor sammen med den andre forelderen kan du ha rett til barnebidrag. Du finner mer informasjon her:',
    'kvittering.ytelserOgTjenester.barnebidrag.link': 'https://www.nav.no/no/person/familie/barnetrygd-og-kontantstotte/barnetrygd#chapter-1',
    'kvittering.ytelserOgTjenester.stoenadTilEnsligMorEllerFar.title': 'Stønad til enslig mor eller far',
    'kvittering.ytelserOgTjenester.stoenadTilEnsligMorEllerFar.text': 'Hvis du er alene med barn finnes det ulike støtteordninger du kan ha rett til. Du finner mer informasjon her:',
    'kvittering.ytelserOgTjenester.stoenadTilEnsligMorEllerFar.link': 'https://www.nav.no/familie/alene-med-barn',

    'signer.alert.1': 'Du har fylt ut opplysninger om far og barn, men har ikke signert skjema. Sjekk om opplysningene stemmer og signer skjema.',
    'signer.alert.2': 'Vil du slette/endre erklæringen, ta kontakt med NAV på telefon 55 55 33 33.',
    'signer.submit': 'Signer',
    'signer.cancel': 'Avbryt',
}
