/* eslint-disable */
export default {
    'two': 'to',
    'three': 'tre',
    'hour': 'time',
    'hours': 'timer',
    'foedselsnummer': 'Fødselsnummer',
    'termindato': 'Termindato',
    'navn': 'Namn',
    'mor': 'Mor',
    'far': 'Far',
    'farskapserklaering': 'Farskapserklæring',

    'read.more': 'Les mer',

    'api.error': 'Oisann, noko gjekk gale.',

    'form.feiloppsummering': 'For å gå vidare må du rette opp følgjande',
    'form.date.placeholder': 'dd.mm.åå',

    'error.taKontakt': 'Ta gjerne kontakt med oss på nav.no/kontakt eller telefon 55 55 33 33 for å få informasjon om korleis du skal gå fram for å få fastsett farskap.',

    'withUserInfoError.banner.title': 'Oops, ',
    'withUserInfoError.banner.text': 'noko gjekk gale',
    'withUserInfoError.title': 'Det oppstod ein feil da vi henta brukarinformasjonen.',
    'withUserInfoError.text': 'Ver vennleg og prøv igjen seinare.',

    'breadcrumbs.forside': 'Farskapserklæring',
    'breadcrumbs.oversikt': 'Farskapserklæringane dine',
    'breadcrumbs.skjema': 'Skjema: Farskapserklæring',
    'breadcrumbs.kvittering': 'Kvittering',
    'breadcrumbs.signer': 'Signer farskapserklæringa',
    'breadcrumbs.avbrutt': 'Signering avbroten',

    'header.forside': 'Farskapserklæring',
    'header.oversikt': 'Farskapserklæringane dine',
    'header.skjema': 'Skjema: Farskapserklæring',
    'header.kvittering': 'Kvittering',
    'header.signer': 'Signer farskapserklæringa',
    'header.avbrutt': 'Signering er avbroten',

    'farskapserklaering.aboutChildren': 'Gjeld barn',
    'farskapserklaering.expectingChildren': 'Ventar barn',
    'farskapserklaering.bornChildren': 'Født/fødde barn',
    'farskapserklaering.parents': 'Foreldre',
    'farskapserklaering.borSammen': 'Bur saman',
    'farskapserklaering.borSammen.yes': 'Ja',
    'farskapserklaering.borSammen.no': 'Nei',

    'forside.title': 'Kva inneber det å erklære farskap?',

    'forside.naarErklaeres.title': 'Når må farskapen erklærast?',
    'forside.naarErklaeres.content.1': 'Når foreldra til barnet ikkje er gifte med kvarandre, følgjer ikkje farskapen direkte av lova.',
    'forside.naarErklaeres.content.2': 'Det vanlege i slike tilfelle er at farskapen blir etablert ved at mora gir opp kven som er faren, og at han erklærer farskapen. Farskap kan erklærast digitalt ved at begge foreldra idfentifiserer seg elektronisk på ein sikker måte og signerer ei digital erklæring.',

    'forside.rettigheter.title': 'Rettar og plikter',
    'forside.rettigheter.content': 'Å erklære farskap for et barn gir faren både rettar og plikter overfor barnet, som for eksempel',
    'forside.rettigheter.arv.title': 'Arv',
    'forside.rettigheter.arv.content': 'Når farskapen er gyldig fastsett, har barnet arverett etter far.',
    'forside.rettigheter.foreldreansvar.title': 'Foreldreansvar',
    'forside.rettigheter.foreldreansvar.content.1': 'Foreldreansvar er den retten og plikta foreldra har til å bestemme over barnet i personlege forhold. Foreldra skal  utøve foreldreansvaret ut frå behova og interessene til barnet. Den eller dei som har foreldreansvar, er også verjer for barnet.',
    'forside.rettigheter.foreldreansvar.content.2': 'For barn som blir fødde etter 1. januar 2020, får mor og far felles foreldreansvar. Dette gjeld barn som har gifte foreldre, barn som har sambuande foreldre, og barn som har foreldre som ikkje bur saman.',
    'forside.rettigheter.foreldreansvar.content.3': 'Dersom mor ønskjer å ha foreldreansvaret åleine, må ho melde frå til Folkeregisteret om det innan eitt år frå den dagen farskapen er fastsett. Dersom far ikkje ønskjer å ha foreldreansvar, må han melde frå til Folkeregisteret om det innan eitt år frå den dagen farskapen er fastsett. Dersom mor har meldt inn at ho ønskjer foreldreansvaret åleine og far ønskjer foreldreansvar eller delt foreldreansvar, må han sjølv ta saka til domstolen.',
    'forside.rettigheter.barnebidrag.title': 'Barnebidrag',
    'forside.rettigheter.barnebidrag.content': 'Begge foreldra har plikt til å sørgje for underhaldet av barnet sitt etter evne. Når foreldra ikkje bur saman, må den som ikkje bur fast saman med barnet, betale barnebidrag. Foreldra kan inngå avtale om kor stort barnebidraget skal vere. Dersom foreldra ikkje blir einige, kan kvar av dei krevje at NAV fastset kor stort barnebidraget skal vere. Dersom foreldra ikkje lever saman når barnet blir født, og dei ikkje har gjort avtale om bidraget, skal NAV av eige tiltak fastsetje bidrag til barnet.',
    'forside.rettigheter.samvaer.title': 'Samvær',
    'forside.rettigheter.samvaer.content.1': 'Barnet har rett til samvær med begge foreldra sjølv om dei lever kvar for seg. Foreldra har gjensidig ansvar for at samværsretten blir oppfylt.',
    'forside.rettigheter.samvaer.content.2': 'Ein avtale om foreldreansvar, samvær eller kvar barnet skal bu fast, kan endrast ved ny avtale mellom foreldra. Dersom foreldra ikkje blir einige, kan dei føre saka inn for retten.',
    'forside.rettigheter.navn.title': 'Namn',
    'forside.rettigheter.navn.content': 'Foreldre med foreldreansvar kan velje namn til barnet. Dei må sende melding om namnet til <a>Folkeregisteret</a> (Skatteetaten). Dersom foreldra ikkje gir melding om etternamn innan 6 månader, får barnet namnet til mor.',
    'forside.rettigheter.navn.link': 'https://www.skatteetaten.no/skjema/navnevalg/',
    'forside.rettigheter.linkLabel': '<a>Les meir i lova om farskap.</a>',
    'forside.rettigheter.link': 'https://lovdata.no/dokument/NL/lov/1981-04-08-7',

    'forside.hvem.title': 'Kven kan erklære?',
    'forside.hvem.content.1': 'Begge foreldra må ha norsk fødsels- og personnummer.',
    'forside.hvem.content.2': 'Begge foreldra må vere over 18 år.',

    'forside.naar.title': 'Når kan farskap erklærast digitalt?',
    'forside.naar.content.1': 'Farskap kan erklærast digitalt både før og etter at barnet er født.',
    'forside.naar.content.2': '', // TODO missing

    'forside.hvordan.title': 'Korleis blir farskap erklært elektronisk?',
    'forside.hvordan.foer.title': 'Før fødselen',
    'forside.hvordan.foer.step.1': 'Mor gir opp far',
    'forside.hvordan.foer.step.1.content.1': 'Mor loggar inn i løysinga for farskapserklæring.',
    'forside.hvordan.foer.step.1.content.2': 'Mor gir opp termindatoen.',
    'forside.hvordan.foer.step.1.content.3': 'Mor gir opp namnet og fødselsnummeret til faren (11 siffer).',
    'forside.hvordan.foer.step.1.content.4': 'Mor stadfestar at personen som er gitt opp, er far til barnet.',
    'forside.hvordan.foer.step.2': 'Far erklærer farskap.',
    'forside.hvordan.foer.step.2.content.1': 'Far får melding frå mor eller NAV med lenkje til løysinga.',
    'forside.hvordan.foer.step.2.content.2': 'Far loggar inn og kontrollerer opplysninga.',
    'forside.hvordan.foer.step.2.content.3': 'Far stadfestar at han er kjend med rettsverknadene av å erklære farskap.',
    'forside.hvordan.foer.step.2.content.4': 'Far signerer erklæringa.',
    'forside.hvordan.foer.step.3': 'Erklaringa blir send til Folkeregisteret for å bli registrert og arkivert.',
    'forside.hvordan.etter.title': 'Etter fødselen',
    'forside.hvordan.etter.step.1': 'Mor gir opp far.',
    'forside.hvordan.etter.step.1.content.1': 'Mor loggar inn i løysinga for farskapserklæring.',
    'forside.hvordan.etter.step.1.content.2': 'Mor vel barnet/barna ho vil gi opp faren til.',
    'forside.hvordan.etter.step.1.content.3': 'Mor gir opp namnet og fødselsnummeret til faren.',
    'forside.hvordan.etter.step.1.content.4': 'Mor stadfestar at personen som er gitt opp, er far til barnet.',
    'forside.hvordan.etter.step.2': 'Far erklærer farskap.',
    'forside.hvordan.etter.step.2.content.1': 'Far får melding frå mor eller NAV med lenkje til løysinga.',
    'forside.hvordan.etter.step.2.content.2': 'Far loggar inn og kontrollerer opplysningane.',
    'forside.hvordan.etter.step.2.content.3': 'Far stadfestar at han er kjend med rettsverknadene av å erklære farskap.',
    'forside.hvordan.etter.step.2.content.4': 'Far signerer erklæringa.',
    'forside.hvordan.etter.step.3': 'Erklæringa blir send til Folkeregisteret for å bli registrert og arkivert.',

    'forside.alleredeRegistrert.title': 'Lurer du på om farskapen allereie er registrert?',
    'forside.alleredeRegistrert.content': 'Har du allereie fått barn og både du og far til barnet allereie har signert farskapen, ber vi deg om å kontakte Skattetaten (Folkeregisteret)',
    'forside.alleredeRegistrert.link': 'https://www.skatteetaten.no/nn/person/folkeregister/fodsel-og-namneval/farskap/',

    'forside.loginButton': 'Fyll ut erklæring om farskap.',

    'forside.dinePersonopplysninger.lenkeKnapp': 'Les om korleis NAV behandlar personopplysningane dine',
    'forside.dinePersonopplysninger.title': 'Slik behandlar NAV personopplysningane dine',
    'forside.dinePersonopplysninger.mor.content': 'NAV innhentar følgande opplysningar om deg frå offentlege register før du kan begynne på ei erklæring om farskap:',
    'forside.dinePersonopplysninger.mor.list.1': 'Sivilstand',
    'forside.dinePersonopplysninger.mor.list.2': 'Alder',
    'forside.dinePersonopplysninger.mor.list.3': 'Kjønn',
    'forside.dinePersonopplysninger.mor.list.4': 'Bustadsadresse',
    'forside.dinePersonopplysninger.mor.list.5': 'Familieforhold',
    'forside.dinePersonopplysninger.far.content': 'Mor gir NAV opplysningar om ditt fulle namn og personnummer. I tillegg hentar vi inn følgande opplysningar frå offentlege register før du kan erklære farskap:',
    'forside.dinePersonopplysninger.far.list.1': 'Alder',
    'forside.dinePersonopplysninger.far.list.2': 'Kjønn',
    'forside.dinePersonopplysninger.far.list.3': 'Aktivt personnummer',
    'forside.dinePersonopplysninger.etterSignering': 'Når begge foreldrane har signert erklæringa sendes den til Folkeregisteret/Skatteetaten for registrering og arkivering.',
    'forside.dinePersonopplysninger.personvernerklaering.title': 'Personvernerklæring i NAV',
    'forside.dinePersonopplysninger.personvernerklaering.content': 'Du kan lese meir om korleis NAV behandlar personopplysningar i Arbeids- og velferdsetatens personvernerklæring på <a>nav.no/personvern.</a>',
    'forside.dinePersonopplysninger.personvernerklaering.link': 'https://www.nav.no/no/NAV+og+samfunn/Om+NAV/personvern-i-arbeids-og-velferdsetaten/personvernerkl%C3%A6ring-for-arbeids-og-velferdsetaten',

    //'notPermitted.forelderHarVerge': 'Du er registrert med verge i Folkeregisteret og kan derfor ikke bruke løsningen',
    'notPermitted.ikkeMyndig': 'For at farskap skal kunne erklærast elektronisk, må begge forelda vere over 18 år.',
    'notPermitted.medmorEllerUkjent': 'Medmor eller person med ukjend rolle kan ikkje bruke løysinga.', // TODO: endre tekst
    //'notPermitted.morIkkeNorskBostedsadresse': 'For at farskap skal kunne erklærast elektronisk, må du være registrert med ein norsk bustedsadresse i Folkeregisteret.', // TODO
    'notPermitted.morSivilstandGift.1': 'Du er gift, og ektefellen din blir automatisk regisrert som far til barn du føder. Dersom det er ein annan mann enn ektefellen din som er far til barnet, kan farskapen endrast. Dette kan ikkje gjerast elektronisk.',
    'notPermitted.morSivilstandGift.2': 'Du finn meir informasjon om å endre farskap <a>her</a>. Du er også velkomen til å kontakte oss på nav.no/kontakt eller telefon 55 55 33 33',
    'notPermitted.morSivilstandGift.link': 'https://www.nav.no/no/person/familie/farskap-og-morskap',
    'notPermitted.morSivilstandPartner.1': 'Du er gift / registrert partnar, og du og ektefellen/partnaren din må sende ein søknad til skatteeteaten for å få medmorskap registrert.',
    'notPermitted.morSivilstandPartner.2': 'Du finn informasjon og søknadsskjema <a>her</a>.',
    'notPermitted.morSivilstandPartner.link': 'https://www.skatteetaten.no/nn/person/folkeregister/fodsel-og-namneval/soknad-om-medmorskap/',
    'notPermitted.morSivilstandUoppgitt': 'Du har ikkje gitt opp sivilstand og kan ikkje opprette farskapserklæring.', // TODO: endre tekst

    'oversikt.infoPanel.greeting': 'Hei, {fornavn}',

    'oversikt.infoPanel.common.forBarn.termindato': 'forventa født {termindato}',
    'oversikt.infoPanel.common.forBarn.foedselsnummer': 'med fødselsnr. {fnr}',

    'oversikt.infoPanel.mor.utenBarn.1': 'Dersom du er minimum 22 veker på veg, kan du gi opp termindatoen og gi opplysningar om far til barnet slik at han kan erklære farskapen elektronisk.',
    'oversikt.infoPanel.mor.utenBarn.2': 'Du må ha fullt namn og fødselsnummer til mannen du gir opp som far til barnet.',
    'oversikt.infoPanel.mor.medBarn.1.single': 'Vi har fått opplysningar om barnet du nettopp har født:',
    'oversikt.infoPanel.mor.medBarn.1.multiple': 'Vi har fått opplysningar om dei nyleg fødte barna dine:',
    'oversikt.infoPanel.mor.medBarn.2': 'Ifølgje opplysningane våre er farskapen ikkje fastsett for barnet nemnt over. Dersom du gir opplysningar om far til barnet nedanfor, kan han erklære farskapen elektronisk. Hugs at du må ha fullt namn og fødselsnummer til mannen du gir opp som far.',
    'oversikt.infoPanel.mor.ikkeSignert.1': 'Du har begynt på ei erklæring for barn.',
    'oversikt.infoPanel.mor.ikkeSignert.2': 'Dersom opplysningane du har gitt om far til barnet, ikkje stemmer, eller du er usikker på kven som er far til barnet, kan du slette erklæringa ved å ta kontakt med NAV på nav.no/kontakt eller telefon 55 55 33 33.',
    'oversikt.infoPanel.mor.farIkkeSignert.1': 'Du har tidlegare gitt opplysningar om far til barn.',
    'oversikt.infoPanel.mor.farIkkeSignert.2': 'Faren du har gitt opp, har ikkje erklært farskapen til barnet. Når han erklærer farskapen, blir erklæringa send over til Skatteetaten for å bli registrert. Ein kopi av erklæringa blir også send til adressa du har registrert hos NAV.',
    'oversikt.infoPanel.mor.farSignert.1': 'Du har gitt opplysningar om far til barnet, som er',
    'oversikt.infoPanel.mor.farSignert.2': ', og oppgitt far har erklært farskap for barnet.',
    'oversikt.infoPanel.mor.farSignert.3': 'Erklæringa er send over til Skatteetaten for å bli registrert. Ein kopi av erklæringa er send til e-postadressa du har registrert hos NAV.',

    'oversikt.infoPanel.far.utenErklaering': 'Det er inga farskapserklæring som ventar på signaturen din. For at du skal kunne erklære farskap elektronisk, må mor til barnet først gi opp det som far til barnet.',
    'oversikt.infoPanel.far.ikkeSignert': 'Du er gitt opp som far til barnet.', // TODO
    'oversikt.infoPanel.far.signert': 'Du har erklært farskap, og erklæringa er send over Folkeregisteret for å bli registrert. Ein kopi av erklæringa er også send til adressa du har registrert hos NAV.', // TODO

    'oversikt.ventendeErklaeringer.title': 'Oversikt',

    'oversikt.moreInfoPanels.erFarskapRegistrert.title': 'Er du usikker på om farskapen til barnet er registrert?',
    'oversikt.moreInfoPanels.erFarskapRegistrert.content': 'Dersom du allereie har født eit barn og lurer på om farskapen er registrert, ber vi deg ta kontatk med Skatteetaten. Du finn meir informasjon om registrering av farskap <a>her</a>. Dersom du tidlegare har erklært farskap elektronisk, skal erklæringa vere send til e-postadressa du har registrert hos NAV.',
    'oversikt.moreInfoPanels.erFarskapRegistrert.link': 'https://www.skatteetaten.no/nn/person/folkeregister/fodsel-og-namneval/barn-fodt-i-norge/',
    'oversikt.moreInfoPanels.hvemErFar.title': 'Er du usikker på kven som er far til barnet?',
    'oversikt.moreInfoPanels.hvemErFar.content': 'Dersom du ikkje har fullt namn og fødselsnummer eller er usikker på kven som er far til barnet, kan du ikkje bruke løysinga. Dersom farskapen ikkje er fastsett når barnet blir født, vil vi kontakte deg for å få fastsett farskapen. Dersom du lurer på saksgangen eller andre ting, kan du kontakte oss på nav.no/kontakt eller telefon 55 55 33 33.',
    'oversikt.moreInfoPanels.medmor.title': 'Ønskjer du å gi opp medmor?',
    'oversikt.moreInfoPanels.medmor.content.1': 'Ei medmor er ei kvinne som har fått juridisk foreldrestatus for det biologiske barnet til den kvinnelege ektefellen eller sambuaren sin. Dersom du er sambuar med ei kvinne, kan de søkje om medmorskap dersom barnet er blitt til ved assistert befruktning.',
    'oversikt.moreInfoPanels.medmor.content.2': 'Du finn informasjon og søknadsskjema <a>her</a>.',
    'oversikt.moreInfoPanels.medmor.content.link': 'https://www.skatteetaten.no/nn/person/folkeregister/fodsel-og-namneval/soknad-om-medmorskap/',
    'oversikt.moreInfoPanels.hvaSkjerNaa.title': 'Kva skjer no?',
    'oversikt.moreInfoPanels.hvaSkjerNaa.content': 'Det er Skatteetaten ved Folkeregisteret som er ansvarleg for å registrere og arkivere farskapserklæringar. Når de melder inn opplysningar om namnet til barnet til dei, vil du få ei stadfesting på at fødselsnummeret og namnet er registrert. Stadfestinga får du i innboksen din i Altinn. Du finn meir informasjon om å registrere farskap og å velje namn <a>her</a>.',
    'oversikt.moreInfoPanels.hvaSkjerNaa.link': 'https://www.skatteetaten.no/nn/person/folkeregister/fodsel-og-namneval/barn-fodt-i-norge/',
    'oversikt.moreInfoPanels.farErklaererIkke.title': 'Kva skjer dersom faren du har gitt opp, ikkje erklærer farskapen?',
    'oversikt.moreInfoPanels.farErklaererIkke.content': 'Dersom faren du har gitt opp, ikkje erklærer farskapen, har NAV ansvaret for å fastsetje han. Det kan då vere aktuelt å kalle inn partane og stadfeste farskapen ved å bruke DNA-analyse. For meir informasjon kan du kontakte oss på nav.no/kontakt eller telefon 55 55 33 33.',
    'oversikt.moreInfoPanels.erklaereUtenMor.title': 'Vil du erklære farskap for eit barn utan at mor til barnet har gitt opp deg som far til barnet?',
    'oversikt.moreInfoPanels.erklaereUtenMor.content.1': 'Dersom du ønskjer å erklære farskap for eit barn og du ikkje er blitt gitt opp som far, kan du møte personleg på ein av desse stadene.',
    'oversikt.moreInfoPanels.erklaereUtenMor.content.li.1': 'Lege/jordmor i samband med svangerskapskontroll/fødsel',
    'oversikt.moreInfoPanels.erklaereUtenMor.content.li.2': 'Skattekontor',
    'oversikt.moreInfoPanels.erklaereUtenMor.content.li.3': 'NAV-kontor',
    'oversikt.moreInfoPanels.erklaereUtenMor.content.li.4': 'Dommar',
    'oversikt.moreInfoPanels.erklaereUtenMor.content.li.5': 'Norsk diplomatisk eller konsulær tenestemann, dersom du er i utlandet.',
    'oversikt.moreInfoPanels.erklaereUtenMor.content.2': 'Hugs å ta med legitimasjon',
    'oversikt.moreInfoPanels.erklaereUtenMor.content.3': 'For meir informasjon sjå <a>farskap og foreldreskap</a>, kontakt oss på nav,no/kontakt eller telefon 55 55 33 33. Vi gjer merksam på at dersom barnet er født i utlandet, må mora ha gitt opp deg som far til barnet før du kan erklære farskap.',
    'oversikt.moreInfoPanels.erklaereUtenMor.content.3.link': 'https://www.nav.no/no/person/familie/farskap-og-morskap/farskap-og-foreldreansvar',
    'oversikt.moreInfoPanels.alleredeErklaert.title': 'Har du allereie erklært farskap og lurer på kva som skjer no?',
    'oversikt.moreInfoPanels.alleredeErklaert.content.1': 'Det er Skatteetaten ved Folkeregisteret som er ansvarleg for å registrere og arkivere farskapserklæringar. Når de melder inn opplysningar om namnet på barnet til dei, vil du få ei stadfesting på at fødselsnummeret og namnet er registrert. Stadfestinga får du i innboksen din i Altinn.',
    'oversikt.moreInfoPanels.alleredeErklaert.content.2': ' Du finn meir informasjon om å registrere farskap og å velje namn <a>her</a>.',
    'oversikt.moreInfoPanels.alleredeErklaert.link': 'https://www.skatteetaten.no/nn/person/folkeregister/fodsel-og-namneval/barn-fodt-i-norge/',
    'oversikt.moreInfoPanels.erJegFar.title': 'Kva gjer eg dersom eg er usikker på om eg er far til barnet?',
    'oversikt.moreInfoPanels.erJegFar.content': 'Dersom du erklærer farskap for barnet, kan du ikkje seinare trekkje erklæringa tilbake. Dersom du er usikker på om du er far til barnet, bør du derfor ikkje signere erklæringa. NAV vil då ta ansvar for at farskapen blir fastsett. Du kan i så fall bli kalla inn og beden om å gi prøve til DNA-analyse. For meir informasjon kan du kontakte oss på nav.no/kontakt eller telefon 55 55 33 33.',

    'oversikt.barn.link.title': 'Opprett farskapserklæring for barn.',
    'oversikt.barn.link.status': 'Dette barnet har ikkje ein registrert far i Folkeregisteret.',

    'oversikt.erklaeringer.link.forelder.mor': 'frå ',
    'oversikt.erklaeringer.link.forelder.far': 'med ',
    'oversikt.erklaeringer.link.status.signering-bruker': 'Ventar på at du skal signere',
    'oversikt.erklaeringer.link.status.signering-motpart': 'Ventar på at motparten skal signere',
    'oversikt.erklaeringer.link.status.registrering': 'Signert og send til Folkeregisteret',
    'oversikt.goToSkjemaButton': 'Opprett farskapserklæring',

    'skjema.next': 'Neste',
    'skjema.cancel': 'Avbryt',
    'skjema.edit': 'Endre',
    'skjema.submit': 'Signer farskapserklæringa',

    'skjema.borSammen.description.intro': 'Foreldre som ikkje bur saman med barnet, har plikt til å betale barnebidrag.',
    'skjema.borSammen.description.content': 'Når foreldra ikkje bur saman når barnet blir født, og heller ikkje har inngått ein avtale om barnebidrag, skal NAV ta opp bidragssak og fastsetje bidrag på eige initiativ. Dersom de inngår ein avtale og sender informasjonen om dette til oss, vil vi ikkje ta opp bidragssak. Les mer om barnebidrag <a>her</a>.',
    'skjema.borSammen.description.content.link': 'https://www.nav.no/barnebidrag',
    'skjema.borSammen.label.yes': 'Ja',
    'skjema.borSammen.label.no': 'Nei',
    'skjema.borSammen.validation.required': 'Opplysinga er påkravd.',

    'skjema.confirm.validation.required': 'Du må stadfeste før søknaden kan sendast inn.',

    'skjema.mor.barn.title': 'Gjeld barn',
    'skjema.mor.barn.description': 'Legg inn termindatoen slik han er berekna i ultralydundersøkinga. Dersom du har fått ein dato for planlagt keisarsnitt, legg du inn denne datoen som termindato. Du må vere minst 22 veker på veg for å opprette ei erklæring.',
    'skjema.mor.barn.termindato.validation.required': 'Termindato er påkravd.',
    'skjema.mor.barn.termindato.validation.pattern': 'Ugyldig dato',
    'skjema.mor.barn.termindato.validation.minDate': 'Kan ikkje vere meir enn tre veker tilbake i tid',
    'skjema.mor.barn.termindato.validation.maxDate': 'Datoen er meir enn 40 veker fram i tid. Vent til veke 22 av svangerskapet med å stadfeste far til barnet.',
    'skjema.mor.barn.termindato.validation.beforeWeek22': 'Du er i veke {weekNr} i svangerskapet. Vent til veke 22 med å stadfeste far til barnet.',
    'skjema.mor.far.title': 'Far til barnet',
    'skjema.mor.far.navn.label': 'Namn',
    'skjema.mor.far.navn.description.1': 'Gi opp fullt namn slik det står i Folkeregisteret.',
    'skjema.mor.far.navn.description.2': 'Skriv namnet slik: fornamn mellomamn etternamn',
    'skjema.mor.far.navn.validation.required': 'Namnet til faren er påkravd.',
    'skjema.mor.far.foedselsnummer.label': 'Fødselsnummer',
    'skjema.mor.far.foedselsnummer.validation.required': 'Fødselsnummeret til faren er påkravd.',
    'skjema.mor.far.foedselsnummer.validation.fnr': 'Ugyldig fødselsnummer',
    'skjema.mor.far.validation.farHarIkkeFnummer': 'Farskap kan ikkje erklærast elektronisk hvis far kun er registrert med d-nummer i Folkeregisteret.', // TODO
    'skjema.mor.far.validation.feilRolleFar.1': 'Medmor kan ikkje erklærast elektronisk. Dersom du er sambuar med ei kvinne, kan de søkje Skatteetaten om medmorskap dersom barnet er blitt til ved hjelp av assistert befruktning.',
    'skjema.mor.far.validation.feilRolleFar.2': 'Du finn informasjon og søknadsskjema <a>her</a>.',
    'skjema.mor.far.validation.feilRolleFar.link': 'https://www.skatteetaten.no/nn/person/folkeregister/fodsel-og-namneval/soknad-om-medmorskap/',
    'skjema.mor.far.validation.forskjelligeFedre': 'Du kan ikkje opprette farskapserklæringar med forskjellige fedrar for same kull nyfødte.', // TODO: skal denne kunne oppstå? Kanskje ikke tillate mor å taste inn annen far?
    'skjema.mor.far.validation.pdlPersonIkkeFunnet': 'Fødselsnummeret du har gitt opp, finst ikkje i Folkeregisteret.',
    'skjema.mor.far.validation.defaultUgyldigFarMessage': 'Den oppgitte faren kan ikkje erklære farskap digitalt. Ta kontakt med NAV på nav.no/kontakt eller telefon 55 55 33 33 for meir informasjon.',
    'skjema.mor.far.validation.maksAntallForsoek.1': 'Du har tasta feil fødselsnummer/namn på oppgitt far tre gonger, og er no blitt blokkert frå løysinga.',
    'skjema.mor.far.validation.maksAntallForsoek.2': 'Du kan prøve på nytt igjen om {timerIgjenForNullstillingAvForsoek} {tidsEnhet}.',
    'skjema.mor.far.validation.morOgFarSammePerson': 'Du kan ikkje oppgi deg selv som far.', // TODO
    'skjema.mor.far.validation.navnStemmerIkkeMedRegister.1': 'Namnet og/eller fødselsnummeret til barnet er feil.',
    'skjema.mor.far.validation.navnStemmerIkkeMedRegister.2': 'Sjekk at namnet er stava rett, og at fødselsnummeret stemmer.',
    'skjema.mor.far.validation.resterendeForsoek': 'Du har tasta feil fødsesnummer/namn på oppgitt far {incorrectAttempts} gonger. Ver vennleg og be far til barnet om å sjekke korleis namnet hans er skrive i Folkeregisteret, før du prøver på nytt. Dersom du tastar feil fem gonger, blir du blokkert frå løysinga.',
    'skjema.mor.far.validation.resterendeForsoek.final': 'Du har tasta feil fødselsnummer/namn på oppgitt far to gonger og har berre eitt forsøk igjen før du blir blokkert frå løysinga.',
    // 'skjema.mor.spraak.title': '',
    // 'skjema.mor.spraak.description': '',
    // 'skjema.mor.spraak.label.norwegian': '',
    // 'skjema.mor.spraak.label.english': '',
    // 'skjema.mor.spraak.validation.required': '',
    'skjema.mor.confirm.title': 'Stadfest opplysningane om far til barnet.',
    'skjema.mor.confirm.farCorrect.label': 'Eg godkjenner at opplysningane om far til barnet er korrekte.',
    'skjema.mor.confirm.cannotWithdraw.label': 'Eg er klar over at eg ikkje kan trekkje tilbake denne stadfestinga seinare.',
    'skjema.confirm.signeringPostenInfo': 'Du blir send vidarte til Posten si løysing for signering.',

    'skjema.far.borSammen.title': 'Bur du saman med mor til barnet?',
    'skjema.far.lesOpplysninger.title': 'Les opplysningane som er gitt opp av mor til barnet.',
    'skjema.far.confirm.title': 'Signer farskapserklæringa',
    'skjema.far.confirm.readAndUnderstood.label': 'Eg har lese og forstått kva farskapserklæringa inneber.',
    'skjema.far.confirm.cannotWithdraw.label': 'Eg er kjend med at denne stadfestinga ikkje kan trekkjast tilbake på eit seinare tidspunkt.',

    'kvittering.intro.foedselsnummer': 'med fødselsnummer',
    'kvittering.intro.termindato': 'forventa født',
    'kvittering.intro.downloadPdfNotSigned': 'Du kan laste ned farskapserklæringa som ein pdf på denne sida etter at begge partane har signert.',
    'kvittering.intro.downloadPdf': 'Last ned ferdig signert farskapserklæring som pdf her: ',
    'kvittering.intro.pdfName': 'Farskapserklæring.pdf',
    'kvittering.intro.mor.1': 'Vi har fått opplysningane dine om far.',
    'kvittering.intro.mor.2': 'Erklæringa blir send vidare til han for å bli godkjend og signert.',
    'kvittering.intro.mor.3': 'Du kan ikkje endre opplysningane du har gitt.',
    'kvittering.intro.mor.4': 'Du kan finne igjen erklæringane her: ',
    'kvittering.intro.mor.farSignert': 'Far har {date} erklært farskap for barn.',

    'kvittering.intro.far.1': 'Du har signert farskapserklæring {date} for barn.',
    'kvittering.intro.far.2': 'Erklæringa er endeleg og kan ikkje endrast.',
    'kvittering.intro.far.3': 'Du kan finne igjen erklæringa her: ',
    'kvittering.morAlert.1': 'Erklæringa er ikkje gyldig før oppgitt far har signert.',
    'kvittering.morAlert.2': 'Han kan allereie no logge seg inn på Ditt NAV og signere erklæringa. Vi vil også sende han ei påminning på e-post og/eller sms.',
    'kvittering.prosessIndikator.step.1': 'Mor oppgir far.',
    'kvittering.prosessIndikator.step.2': 'Far erklærer farskap.',
    'kvittering.prosessIndikator.step.3': 'Erklæringa blir send over til Folkeregisteret for å bli registrert og arkivert.',
    'kvittering.hvaSkjerVidere.title': 'Kva skjer vidare?',
    'kvittering.hvaSkjerVidere.1': 'Det er Skatteetaten ved Folkeregisteret som har ansvaret for å registrere og arkivere farskapserklæringar. De vil få oversendt erklæringa når de begge har signert henne. Etter at de har valt namnet til barnet, får du ei stadfesting på at fødselsnummeret og namet er registrert. Stadfestinga får du i innboksen din i Altinn.',
    'kvittering.hvaSkjerVidere.2': 'Fleire opplysningar finn du her:',
    'kvittering.hvaSkjerVidere.link': 'https://www.skatteetaten.no/nn/person/folkeregister/fodsel-og-namneval/',
    'kvittering.hvaSkjerHvis.title': 'Kva skjer dersom?',
    'kvittering.hvaSkjerHvis.farSignererIkke.title': 'Faren du har gitt opp, ikkje signerer erklæringa',
    'kvittering.hvaSkjerHvis.farSignererIkke.termindato.text': 'Dersom faren du har gitt opp, ikkje har signert erklæringa innan éin månad etter fødselen, kontaktar vi deg for å fastsetje farskapen. Dersom far til barnet gløymer å signere erklæringa, ber vi om at du minner han på dette.',
    'kvittering.hvaSkjerHvis.farSignererIkke.foedselsnummer.text': 'Dersom den oppgitte faren ikkje signerer erklæringa innan éin månad, blir du kontakta av NAV for å få fastsett farskapen. Dersom far har gløymt å signere erklæringa, ber vi om at du minner han på dette.',
    'kvittering.hvaSkjerHvis.foedtIUtlandet.title': 'Barnet blir født i utlandet.',
    'kvittering.hvaSkjerHvis.foedtIUtlandet.text': 'Den elektroniske erklæringa er ikkje gyldig dersom barnet blir født i utlandet. Dersom dette skjer, må de erklære farskapen på nytt på papir.',
    'kvittering.hvaSkjerHvis.barnetDoer.title': 'Barnet døyr',
    'kvittering.hvaSkjerHvis.barnetDoer.text': 'Dersom barnet døyr før svangerskapet er fullgått, blir farskapen i enkelte tilfelle likevel registrert. Vi ber deg kontakte Skatteetaten dersom du har spørsmål om dette. ',
    'kvittering.ytelserOgTjenester.title': 'Relaterte ytingar og tenester frå NAV',
    'kvittering.ytelserOgTjenester.foreldrepengerSvangerskapspengerEngangsstoenad.title': 'Foreldrepengar, svangerskapspengar og eingongsstønad',
    'kvittering.ytelserOgTjenester.foreldrepengerSvangerskapspengerEngangsstoenad.text': 'Du finn informasjon om kva rettar du har, og søknadsskjema her:',
    'kvittering.ytelserOgTjenester.foreldrepengerSvangerskapspengerEngangsstoenad.link': 'https://familie.nav.no',
    'kvittering.ytelserOgTjenester.barnetrygd.title': 'Barnetrygd',
    'kvittering.ytelserOgTjenester.barnetrygd.text': 'Du treng som hovudregel ikkje å søkje om barnetrygd. Dersom barnet blir født i Noreg, vil mor til barnet automatisk få barnetrygd omtrent 2 månader etter fødselen. Du finn meir informasjon om retten til barnetrygd her:',
    'kvittering.ytelserOgTjenester.barnetrygd.link': 'https://www.nav.no/no/person/familie/barnetrygd-og-kontantstotte/nynorsk/barnetrygd#chapter-1',
    'kvittering.ytelserOgTjenester.utvidetBarnetrygd.title': 'Utvida barnetrygd',
    'kvittering.ytelserOgTjenester.utvidetBarnetrygd.text': 'Dersom du er einsleg mor eller far, kan du søkje om utvida barnetrygd. Du finn meir informasjon her:',
    'kvittering.ytelserOgTjenester.utvidetBarnetrygd.link': 'https://www.nav.no/no/person/familie/barnetrygd-og-kontantstotte/nynorsk/barnetrygd#chapter-1',
    'kvittering.ytelserOgTjenester.barnebidrag.title': 'Barnebidrag',
    'kvittering.ytelserOgTjenester.barnebidrag.text': 'Dersom du ikkje bur saman med den andre forelderen, kan du ha rett til barnebidrag. Du finn meir informasjon her:',
    'kvittering.ytelserOgTjenester.barnebidrag.link': 'https://www.nav.no/no/person/familie/barnetrygd-og-kontantstotte/nynorsk/barnetrygd#chapter-1',
    'kvittering.ytelserOgTjenester.stoenadTilEnsligMorEllerFar.title': 'Stønad til einsleg mor eller far',
    'kvittering.ytelserOgTjenester.stoenadTilEnsligMorEllerFar.text': 'Dersom du er åleine med barn, finst det ulike støtteordningar du kan ha rett til. Du finn meir informasjon her:',
    'kvittering.ytelserOgTjenester.stoenadTilEnsligMorEllerFar.link': 'https://www.nav.no/familie/alene-med-barn',

    'signer.alert.1': 'Du har fylt ut opplysningar om far og barn, men har ikkje signert skjemaet. Sjekk om opplysningane stemmer, og signer skjemaet.',
    'signer.alert.2': 'Vil du slette eller endre erklæringa, ta kontakt med NAV på nav.no/kontakt eller telefon 55 55 33 33.',
    'signer.submit': 'Signer',
    'signer.cancel': 'Avbryt',

    'avbrutt.alert.mor': '',
    'avbrutt.alert.far': '',
};
